# fly.toml app configuration file generated for nfl-betting-lines-milecav8 on 2024-10-12T18:52:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nfl-betting-lines-milecav8'
primary_region = 'ewr'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
