const defenseStats = [
    {
        "team": "Los Angeles Chargers",
        "g": "14",
        "points": "247",
        "total_yards": "4714",
        "plays_offense": "878",
        "yds_per_play_offense": "5.4",
        "turnovers": "19",
        "fumbles_lost": "5",
        "first_down": "262",
        "pass_cmp": "300",
        "pass_att": "465",
        "pass_yds": "2962",
        "pass_td": "19",
        "pass_int": "14",
        "pass_net_yds_per_att": "5.9",
        "pass_fd": "141",
        "rush_att": "373",
        "rush_yds": "1752",
        "rush_td": "6",
        "rush_yds_per_att": "4.7",
        "rush_fd": "94",
        "penalties": "84",
        "penalties_yds": "720",
        "pen_fd": "27",
        "score_pct": "32.5",
        "turnover_pct": "12.6",
        "exp_pts_def_tot": "-12.37"
    },
    {
        "team": "Philadelphia Eagles",
        "g": "14",
        "points": "247",
        "total_yards": "3858",
        "plays_offense": "821",
        "yds_per_play_offense": "4.7",
        "turnovers": "16",
        "fumbles_lost": "8",
        "first_down": "244",
        "pass_cmp": "275",
        "pass_att": "445",
        "pass_yds": "2427",
        "pass_td": "15",
        "pass_int": "8",
        "pass_net_yds_per_att": "5.0",
        "pass_fd": "136",
        "rush_att": "337",
        "rush_yds": "1431",
        "rush_td": "9",
        "rush_yds_per_att": "4.2",
        "rush_fd": "87",
        "penalties": "65",
        "penalties_yds": "492",
        "pen_fd": "21",
        "score_pct": "32.4",
        "turnover_pct": "10.3",
        "exp_pts_def_tot": "28.22"
    },
    {
        "team": "Denver Broncos",
        "g": "14",
        "points": "247",
        "total_yards": "4414",
        "plays_offense": "915",
        "yds_per_play_offense": "4.8",
        "turnovers": "23",
        "fumbles_lost": "9",
        "first_down": "265",
        "pass_cmp": "321",
        "pass_att": "509",
        "pass_yds": "3034",
        "pass_td": "17",
        "pass_int": "14",
        "pass_net_yds_per_att": "5.4",
        "pass_fd": "162",
        "rush_att": "357",
        "rush_yds": "1380",
        "rush_td": "7",
        "rush_yds_per_att": "3.9",
        "rush_fd": "69",
        "penalties": "93",
        "penalties_yds": "685",
        "pen_fd": "34",
        "score_pct": "30.7",
        "turnover_pct": "13.5",
        "exp_pts_def_tot": "80.79"
    },
    {
        "team": "Minnesota Vikings",
        "g": "14",
        "points": "252",
        "total_yards": "4676",
        "plays_offense": "895",
        "yds_per_play_offense": "5.2",
        "turnovers": "28",
        "fumbles_lost": "8",
        "first_down": "261",
        "pass_cmp": "338",
        "pass_att": "531",
        "pass_yds": "3429",
        "pass_td": "19",
        "pass_int": "20",
        "pass_net_yds_per_att": "6.0",
        "pass_fd": "176",
        "rush_att": "322",
        "rush_yds": "1247",
        "rush_td": "7",
        "rush_yds_per_att": "3.9",
        "rush_fd": "66",
        "penalties": "115",
        "penalties_yds": "1008",
        "pen_fd": "19",
        "score_pct": "29.9",
        "turnover_pct": "16.9",
        "exp_pts_def_tot": "53.39"
    },
    {
        "team": "Kansas City Chiefs",
        "g": "14",
        "points": "259",
        "total_yards": "4297",
        "plays_offense": "823",
        "yds_per_play_offense": "5.2",
        "turnovers": "16",
        "fumbles_lost": "6",
        "first_down": "256",
        "pass_cmp": "303",
        "pass_att": "464",
        "pass_yds": "3010",
        "pass_td": "18",
        "pass_int": "10",
        "pass_net_yds_per_att": "6.1",
        "pass_fd": "153",
        "rush_att": "327",
        "rush_yds": "1287",
        "rush_td": "11",
        "rush_yds_per_att": "3.9",
        "rush_fd": "79",
        "penalties": "92",
        "penalties_yds": "738",
        "pen_fd": "24",
        "score_pct": "35.3",
        "turnover_pct": "10.8",
        "exp_pts_def_tot": "-21.56"
    },
    {
        "team": "Pittsburgh Steelers",
        "g": "14",
        "points": "265",
        "total_yards": "4433",
        "plays_offense": "843",
        "yds_per_play_offense": "5.3",
        "turnovers": "30",
        "fumbles_lost": "15",
        "first_down": "258",
        "pass_cmp": "301",
        "pass_att": "475",
        "pass_yds": "3112",
        "pass_td": "16",
        "pass_int": "15",
        "pass_net_yds_per_att": "6.1",
        "pass_fd": "150",
        "rush_att": "333",
        "rush_yds": "1321",
        "rush_td": "13",
        "rush_yds_per_att": "4.0",
        "rush_fd": "88",
        "penalties": "108",
        "penalties_yds": "914",
        "pen_fd": "20",
        "score_pct": "31.8",
        "turnover_pct": "17.9",
        "exp_pts_def_tot": "14.36"
    },
    {
        "team": "Detroit Lions",
        "g": "14",
        "points": "282",
        "total_yards": "4701",
        "plays_offense": "835",
        "yds_per_play_offense": "5.6",
        "turnovers": "20",
        "fumbles_lost": "6",
        "first_down": "269",
        "pass_cmp": "299",
        "pass_att": "489",
        "pass_yds": "3283",
        "pass_td": "13",
        "pass_int": "14",
        "pass_net_yds_per_att": "6.3",
        "pass_fd": "157",
        "rush_att": "315",
        "rush_yds": "1418",
        "rush_td": "16",
        "rush_yds_per_att": "4.5",
        "rush_fd": "74",
        "penalties": "93",
        "penalties_yds": "732",
        "pen_fd": "38",
        "score_pct": "34.9",
        "turnover_pct": "13.2",
        "exp_pts_def_tot": "-14.85"
    },
    {
        "team": "Green Bay Packers",
        "g": "14",
        "points": "287",
        "total_yards": "4486",
        "plays_offense": "856",
        "yds_per_play_offense": "5.2",
        "turnovers": "26",
        "fumbles_lost": "12",
        "first_down": "271",
        "pass_cmp": "312",
        "pass_att": "462",
        "pass_yds": "3016",
        "pass_td": "19",
        "pass_int": "14",
        "pass_net_yds_per_att": "6.0",
        "pass_fd": "161",
        "rush_att": "354",
        "rush_yds": "1470",
        "rush_td": "12",
        "rush_yds_per_att": "4.2",
        "rush_fd": "92",
        "penalties": "93",
        "penalties_yds": "808",
        "pen_fd": "18",
        "score_pct": "34.5",
        "turnover_pct": "16.2",
        "exp_pts_def_tot": "3.22"
    },
    {
        "team": "Houston Texans",
        "g": "14",
        "points": "300",
        "total_yards": "4234",
        "plays_offense": "859",
        "yds_per_play_offense": "4.9",
        "turnovers": "28",
        "fumbles_lost": "9",
        "first_down": "249",
        "pass_cmp": "271",
        "pass_att": "470",
        "pass_yds": "2756",
        "pass_td": "27",
        "pass_int": "19",
        "pass_net_yds_per_att": "5.4",
        "pass_fd": "141",
        "rush_att": "344",
        "rush_yds": "1478",
        "rush_td": "7",
        "rush_yds_per_att": "4.3",
        "rush_fd": "78",
        "penalties": "94",
        "penalties_yds": "680",
        "pen_fd": "30",
        "score_pct": "33.5",
        "turnover_pct": "15.9",
        "exp_pts_def_tot": "33.06"
    },
    {
        "team": "Arizona Cardinals",
        "g": "14",
        "points": "306",
        "total_yards": "4738",
        "plays_offense": "853",
        "yds_per_play_offense": "5.6",
        "turnovers": "14",
        "fumbles_lost": "7",
        "first_down": "284",
        "pass_cmp": "307",
        "pass_att": "438",
        "pass_yds": "3038",
        "pass_td": "16",
        "pass_int": "7",
        "pass_net_yds_per_att": "6.4",
        "pass_fd": "167",
        "rush_att": "379",
        "rush_yds": "1700",
        "rush_td": "13",
        "rush_yds_per_att": "4.5",
        "rush_fd": "100",
        "penalties": "71",
        "penalties_yds": "608",
        "pen_fd": "17",
        "score_pct": "44.4",
        "turnover_pct": "9.8",
        "exp_pts_def_tot": "-91.53"
    },
    {
        "team": "Chicago Bears",
        "g": "14",
        "points": "308",
        "total_yards": "4915",
        "plays_offense": "851",
        "yds_per_play_offense": "5.8",
        "turnovers": "21",
        "fumbles_lost": "10",
        "first_down": "267",
        "pass_cmp": "268",
        "pass_att": "423",
        "pass_yds": "3049",
        "pass_td": "14",
        "pass_int": "11",
        "pass_net_yds_per_att": "6.7",
        "pass_fd": "148",
        "rush_att": "395",
        "rush_yds": "1866",
        "rush_td": "17",
        "rush_yds_per_att": "4.7",
        "rush_fd": "101",
        "penalties": "92",
        "penalties_yds": "669",
        "pen_fd": "18",
        "score_pct": "40.5",
        "turnover_pct": "13.7",
        "exp_pts_def_tot": "-38.82"
    },
    {
        "team": "Buffalo Bills",
        "g": "14",
        "points": "310",
        "total_yards": "4837",
        "plays_offense": "866",
        "yds_per_play_offense": "5.6",
        "turnovers": "25",
        "fumbles_lost": "12",
        "first_down": "289",
        "pass_cmp": "329",
        "pass_att": "480",
        "pass_yds": "3189",
        "pass_td": "23",
        "pass_int": "13",
        "pass_net_yds_per_att": "6.2",
        "pass_fd": "181",
        "rush_att": "354",
        "rush_yds": "1648",
        "rush_td": "11",
        "rush_yds_per_att": "4.7",
        "rush_fd": "87",
        "penalties": "99",
        "penalties_yds": "803",
        "pen_fd": "21",
        "score_pct": "36.9",
        "turnover_pct": "16.3",
        "exp_pts_def_tot": "-54.42"
    },
    {
        "team": "Miami Dolphins",
        "g": "14",
        "points": "312",
        "total_yards": "4320",
        "plays_offense": "813",
        "yds_per_play_offense": "5.3",
        "turnovers": "12",
        "fumbles_lost": "5",
        "first_down": "254",
        "pass_cmp": "292",
        "pass_att": "448",
        "pass_yds": "2870",
        "pass_td": "16",
        "pass_int": "7",
        "pass_net_yds_per_att": "6.0",
        "pass_fd": "153",
        "rush_att": "337",
        "rush_yds": "1450",
        "rush_td": "12",
        "rush_yds_per_att": "4.3",
        "rush_fd": "79",
        "penalties": "99",
        "penalties_yds": "821",
        "pen_fd": "22",
        "score_pct": "41.5",
        "turnover_pct": "8.2",
        "exp_pts_def_tot": "-16.31"
    },
    {
        "team": "New Orleans Saints",
        "g": "14",
        "points": "312",
        "total_yards": "5272",
        "plays_offense": "912",
        "yds_per_play_offense": "5.8",
        "turnovers": "16",
        "fumbles_lost": "3",
        "first_down": "288",
        "pass_cmp": "308",
        "pass_att": "494",
        "pass_yds": "3391",
        "pass_td": "14",
        "pass_int": "13",
        "pass_net_yds_per_att": "6.4",
        "pass_fd": "159",
        "rush_att": "381",
        "rush_yds": "1881",
        "rush_td": "16",
        "rush_yds_per_att": "4.9",
        "rush_fd": "106",
        "penalties": "94",
        "penalties_yds": "789",
        "pen_fd": "23",
        "score_pct": "35.9",
        "turnover_pct": "10.5",
        "exp_pts_def_tot": "-61.28"
    },
    {
        "team": "Seattle Seahawks",
        "g": "14",
        "points": "313",
        "total_yards": "4776",
        "plays_offense": "880",
        "yds_per_play_offense": "5.4",
        "turnovers": "16",
        "fumbles_lost": "5",
        "first_down": "279",
        "pass_cmp": "306",
        "pass_att": "465",
        "pass_yds": "2991",
        "pass_td": "21",
        "pass_int": "11",
        "pass_net_yds_per_att": "6.0",
        "pass_fd": "158",
        "rush_att": "383",
        "rush_yds": "1785",
        "rush_td": "11",
        "rush_yds_per_att": "4.7",
        "rush_fd": "95",
        "penalties": "108",
        "penalties_yds": "855",
        "pen_fd": "26",
        "score_pct": "33.5",
        "turnover_pct": "9.9",
        "exp_pts_def_tot": "-11.93"
    },
    {
        "team": "Washington Commanders",
        "g": "14",
        "points": "315",
        "total_yards": "4505",
        "plays_offense": "823",
        "yds_per_play_offense": "5.5",
        "turnovers": "14",
        "fumbles_lost": "9",
        "first_down": "269",
        "pass_cmp": "253",
        "pass_att": "399",
        "pass_yds": "2655",
        "pass_td": "23",
        "pass_int": "5",
        "pass_net_yds_per_att": "6.1",
        "pass_fd": "143",
        "rush_att": "389",
        "rush_yds": "1850",
        "rush_td": "13",
        "rush_yds_per_att": "4.8",
        "rush_fd": "99",
        "penalties": "80",
        "penalties_yds": "666",
        "pen_fd": "27",
        "score_pct": "39.6",
        "turnover_pct": "9.4",
        "exp_pts_def_tot": "-70.14"
    },
    {
        "team": "San Francisco 49ers",
        "g": "14",
        "points": "320",
        "total_yards": "4183",
        "plays_offense": "834",
        "yds_per_play_offense": "5.0",
        "turnovers": "17",
        "fumbles_lost": "6",
        "first_down": "250",
        "pass_cmp": "265",
        "pass_att": "413",
        "pass_yds": "2534",
        "pass_td": "17",
        "pass_int": "11",
        "pass_net_yds_per_att": "5.7",
        "pass_fd": "138",
        "rush_att": "386",
        "rush_yds": "1649",
        "rush_td": "19",
        "rush_yds_per_att": "4.3",
        "rush_fd": "97",
        "penalties": "66",
        "penalties_yds": "517",
        "pen_fd": "15",
        "score_pct": "39.3",
        "turnover_pct": "11.0",
        "exp_pts_def_tot": "-29.13"
    },
    {
        "team": "New York Jets",
        "g": "14",
        "points": "325",
        "total_yards": "4410",
        "plays_offense": "888",
        "yds_per_play_offense": "5.0",
        "turnovers": "12",
        "fumbles_lost": "8",
        "first_down": "286",
        "pass_cmp": "271",
        "pass_att": "433",
        "pass_yds": "2715",
        "pass_td": "13",
        "pass_int": "4",
        "pass_net_yds_per_att": "5.8",
        "pass_fd": "140",
        "rush_att": "416",
        "rush_yds": "1695",
        "rush_td": "18",
        "rush_yds_per_att": "4.1",
        "rush_fd": "106",
        "penalties": "88",
        "penalties_yds": "852",
        "pen_fd": "40",
        "score_pct": "44.4",
        "turnover_pct": "6.9",
        "exp_pts_def_tot": "-79.90"
    },
    {
        "team": "Tampa Bay Buccaneers",
        "g": "14",
        "points": "326",
        "total_yards": "4997",
        "plays_offense": "900",
        "yds_per_play_offense": "5.6",
        "turnovers": "18",
        "fumbles_lost": "11",
        "first_down": "289",
        "pass_cmp": "351",
        "pass_att": "525",
        "pass_yds": "3468",
        "pass_td": "23",
        "pass_int": "7",
        "pass_net_yds_per_att": "6.2",
        "pass_fd": "176",
        "rush_att": "337",
        "rush_yds": "1529",
        "rush_td": "12",
        "rush_yds_per_att": "4.5",
        "rush_fd": "86",
        "penalties": "79",
        "penalties_yds": "760",
        "pen_fd": "27",
        "score_pct": "39.7",
        "turnover_pct": "10.6",
        "exp_pts_def_tot": "-77.61"
    },
    {
        "team": "New York Giants",
        "g": "14",
        "points": "328",
        "total_yards": "4818",
        "plays_offense": "845",
        "yds_per_play_offense": "5.7",
        "turnovers": "11",
        "fumbles_lost": "9",
        "first_down": "263",
        "pass_cmp": "278",
        "pass_att": "397",
        "pass_yds": "2806",
        "pass_td": "19",
        "pass_int": "2",
        "pass_net_yds_per_att": "6.4",
        "pass_fd": "136",
        "rush_att": "407",
        "rush_yds": "2012",
        "rush_td": "14",
        "rush_yds_per_att": "4.9",
        "rush_fd": "108",
        "penalties": "99",
        "penalties_yds": "819",
        "pen_fd": "19",
        "score_pct": "37.3",
        "turnover_pct": "7.3",
        "exp_pts_def_tot": "-76.32"
    },
    {
        "team": "Indianapolis Colts",
        "g": "14",
        "points": "329",
        "total_yards": "5125",
        "plays_offense": "934",
        "yds_per_play_offense": "5.5",
        "turnovers": "21",
        "fumbles_lost": "9",
        "first_down": "291",
        "pass_cmp": "318",
        "pass_att": "456",
        "pass_yds": "3142",
        "pass_td": "20",
        "pass_int": "12",
        "pass_net_yds_per_att": "6.4",
        "pass_fd": "160",
        "rush_att": "445",
        "rush_yds": "1983",
        "rush_td": "14",
        "rush_yds_per_att": "4.5",
        "rush_fd": "111",
        "penalties": "77",
        "penalties_yds": "676",
        "pen_fd": "20",
        "score_pct": "38.0",
        "turnover_pct": "13.3",
        "exp_pts_def_tot": "-43.57"
    },
    {
        "team": "Baltimore Ravens",
        "g": "14",
        "points": "332",
        "total_yards": "4755",
        "plays_offense": "893",
        "yds_per_play_offense": "5.3",
        "turnovers": "12",
        "fumbles_lost": "4",
        "first_down": "288",
        "pass_cmp": "338",
        "pass_att": "526",
        "pass_yds": "3625",
        "pass_td": "24",
        "pass_int": "8",
        "pass_net_yds_per_att": "6.4",
        "pass_fd": "187",
        "rush_att": "323",
        "rush_yds": "1130",
        "rush_td": "12",
        "rush_yds_per_att": "3.5",
        "rush_fd": "62",
        "penalties": "84",
        "penalties_yds": "661",
        "pen_fd": "39",
        "score_pct": "41.4",
        "turnover_pct": "7.9",
        "exp_pts_def_tot": "-74.58"
    },
    {
        "team": "New England Patriots",
        "g": "14",
        "points": "337",
        "total_yards": "4818",
        "plays_offense": "868",
        "yds_per_play_offense": "5.6",
        "turnovers": "11",
        "fumbles_lost": "5",
        "first_down": "284",
        "pass_cmp": "286",
        "pass_att": "432",
        "pass_yds": "3034",
        "pass_td": "22",
        "pass_int": "6",
        "pass_net_yds_per_att": "6.6",
        "pass_fd": "155",
        "rush_att": "409",
        "rush_yds": "1784",
        "rush_td": "13",
        "rush_yds_per_att": "4.4",
        "rush_fd": "101",
        "penalties": "75",
        "penalties_yds": "605",
        "pen_fd": "28",
        "score_pct": "41.7",
        "turnover_pct": "6.3",
        "exp_pts_def_tot": "-107.06"
    },
    {
        "team": "Los Angeles Rams",
        "g": "14",
        "points": "338",
        "total_yards": "4950",
        "plays_offense": "867",
        "yds_per_play_offense": "5.7",
        "turnovers": "16",
        "fumbles_lost": "5",
        "first_down": "283",
        "pass_cmp": "273",
        "pass_att": "425",
        "pass_yds": "3054",
        "pass_td": "23",
        "pass_int": "11",
        "pass_net_yds_per_att": "6.7",
        "pass_fd": "153",
        "rush_att": "411",
        "rush_yds": "1896",
        "rush_td": "13",
        "rush_yds_per_att": "4.6",
        "rush_fd": "102",
        "penalties": "93",
        "penalties_yds": "801",
        "pen_fd": "28",
        "score_pct": "44.8",
        "turnover_pct": "10.5",
        "exp_pts_def_tot": "-90.09"
    },
    {
        "team": "Atlanta Falcons",
        "g": "14",
        "points": "342",
        "total_yards": "4797",
        "plays_offense": "870",
        "yds_per_play_offense": "5.5",
        "turnovers": "14",
        "fumbles_lost": "5",
        "first_down": "279",
        "pass_cmp": "332",
        "pass_att": "468",
        "pass_yds": "3162",
        "pass_td": "27",
        "pass_int": "9",
        "pass_net_yds_per_att": "6.4",
        "pass_fd": "160",
        "rush_att": "379",
        "rush_yds": "1635",
        "rush_td": "7",
        "rush_yds_per_att": "4.3",
        "rush_fd": "105",
        "penalties": "97",
        "penalties_yds": "741",
        "pen_fd": "14",
        "score_pct": "44.4",
        "turnover_pct": "9.2",
        "exp_pts_def_tot": "-70.92"
    },
    {
        "team": "Cleveland Browns",
        "g": "14",
        "points": "356",
        "total_yards": "4773",
        "plays_offense": "860",
        "yds_per_play_offense": "5.6",
        "turnovers": "11",
        "fumbles_lost": "7",
        "first_down": "244",
        "pass_cmp": "255",
        "pass_att": "423",
        "pass_yds": "2978",
        "pass_td": "20",
        "pass_int": "4",
        "pass_net_yds_per_att": "6.5",
        "pass_fd": "138",
        "rush_att": "404",
        "rush_yds": "1795",
        "rush_td": "19",
        "rush_yds_per_att": "4.4",
        "rush_fd": "90",
        "penalties": "82",
        "penalties_yds": "678",
        "pen_fd": "16",
        "score_pct": "33.1",
        "turnover_pct": "5.8",
        "exp_pts_def_tot": "-45.48"
    },
    {
        "team": "Las Vegas Raiders",
        "g": "14",
        "points": "376",
        "total_yards": "4613",
        "plays_offense": "867",
        "yds_per_play_offense": "5.3",
        "turnovers": "9",
        "fumbles_lost": "1",
        "first_down": "269",
        "pass_cmp": "297",
        "pass_att": "450",
        "pass_yds": "2916",
        "pass_td": "25",
        "pass_int": "8",
        "pass_net_yds_per_att": "6.0",
        "pass_fd": "164",
        "rush_att": "385",
        "rush_yds": "1697",
        "rush_td": "12",
        "rush_yds_per_att": "4.4",
        "rush_fd": "82",
        "penalties": "92",
        "penalties_yds": "667",
        "pen_fd": "23",
        "score_pct": "44.7",
        "turnover_pct": "6.0",
        "exp_pts_def_tot": "-67.53"
    },
    {
        "team": "Jacksonville Jaguars",
        "g": "14",
        "points": "377",
        "total_yards": "5549",
        "plays_offense": "917",
        "yds_per_play_offense": "6.1",
        "turnovers": "8",
        "fumbles_lost": "3",
        "first_down": "321",
        "pass_cmp": "323",
        "pass_att": "471",
        "pass_yds": "3700",
        "pass_td": "27",
        "pass_int": "5",
        "pass_net_yds_per_att": "7.4",
        "pass_fd": "184",
        "rush_att": "420",
        "rush_yds": "1849",
        "rush_td": "16",
        "rush_yds_per_att": "4.4",
        "rush_fd": "108",
        "penalties": "90",
        "penalties_yds": "697",
        "pen_fd": "29",
        "score_pct": "46.9",
        "turnover_pct": "4.8",
        "exp_pts_def_tot": "-157.69"
    },
    {
        "team": "Tennessee Titans",
        "g": "14",
        "points": "379",
        "total_yards": "4164",
        "plays_offense": "831",
        "yds_per_play_offense": "5.0",
        "turnovers": "16",
        "fumbles_lost": "6",
        "first_down": "259",
        "pass_cmp": "274",
        "pass_att": "412",
        "pass_yds": "2551",
        "pass_td": "23",
        "pass_int": "10",
        "pass_net_yds_per_att": "5.8",
        "pass_fd": "134",
        "rush_att": "391",
        "rush_yds": "1613",
        "rush_td": "16",
        "rush_yds_per_att": "4.1",
        "rush_fd": "89",
        "penalties": "100",
        "penalties_yds": "828",
        "pen_fd": "36",
        "score_pct": "39.9",
        "turnover_pct": "9.2",
        "exp_pts_def_tot": "-55.38"
    },
    {
        "team": "Dallas Cowboys",
        "g": "14",
        "points": "380",
        "total_yards": "4984",
        "plays_offense": "860",
        "yds_per_play_offense": "5.8",
        "turnovers": "19",
        "fumbles_lost": "7",
        "first_down": "279",
        "pass_cmp": "284",
        "pass_att": "419",
        "pass_yds": "3079",
        "pass_td": "21",
        "pass_int": "12",
        "pass_net_yds_per_att": "6.7",
        "pass_fd": "144",
        "rush_att": "399",
        "rush_yds": "1905",
        "rush_td": "22",
        "rush_yds_per_att": "4.8",
        "rush_fd": "113",
        "penalties": "117",
        "penalties_yds": "892",
        "pen_fd": "22",
        "score_pct": "42.5",
        "turnover_pct": "11.9",
        "exp_pts_def_tot": "-85.49"
    },
    {
        "team": "Cincinnati Bengals",
        "g": "14",
        "points": "387",
        "total_yards": "5126",
        "plays_offense": "907",
        "yds_per_play_offense": "5.7",
        "turnovers": "20",
        "fumbles_lost": "8",
        "first_down": "308",
        "pass_cmp": "311",
        "pass_att": "477",
        "pass_yds": "3349",
        "pass_td": "26",
        "pass_int": "12",
        "pass_net_yds_per_att": "6.7",
        "pass_fd": "166",
        "rush_att": "405",
        "rush_yds": "1777",
        "rush_td": "18",
        "rush_yds_per_att": "4.4",
        "rush_fd": "115",
        "penalties": "86",
        "penalties_yds": "730",
        "pen_fd": "27",
        "score_pct": "42.1",
        "turnover_pct": "12.5",
        "exp_pts_def_tot": "-114.52"
    },
    {
        "team": "Carolina Panthers",
        "g": "14",
        "points": "418",
        "total_yards": "5407",
        "plays_offense": "939",
        "yds_per_play_offense": "5.8",
        "turnovers": "14",
        "fumbles_lost": "7",
        "first_down": "330",
        "pass_cmp": "292",
        "pass_att": "428",
        "pass_yds": "2985",
        "pass_td": "27",
        "pass_int": "7",
        "pass_net_yds_per_att": "6.6",
        "pass_fd": "166",
        "rush_att": "485",
        "rush_yds": "2422",
        "rush_td": "19",
        "rush_yds_per_att": "5.0",
        "rush_fd": "136",
        "penalties": "97",
        "penalties_yds": "800",
        "pen_fd": "28",
        "score_pct": "49.0",
        "turnover_pct": "8.4",
        "exp_pts_def_tot": "-146.00"
    }
]

const advancedDefenseStats = [
    {
        "g": "14",
        "pass_att_opp": "468",
        "pass_cmp_opp": "332",
        "pass_yds_opp": "3162",
        "pass_td_opp": "27",
        "def_tgt_yds_per_att": "7.1",
        "def_air_yds": "1728",
        "def_yac": "1569",
        "blitzes": "111",
        "blitz_pct": "21.2%",
        "qb_hurry": "43",
        "qb_hurry_pct": "8.2%",
        "qb_knockdown": "38",
        "qb_knockdown_pct": "8.1%",
        "sacks": "23",
        "pressures": "104",
        "pressures_pct": "19.8%",
        "tackles_missed": "86"
    },
    {
        "g": "14",
        "pass_att_opp": "480",
        "pass_cmp_opp": "329",
        "pass_yds_opp": "3189",
        "pass_td_opp": "23",
        "def_tgt_yds_per_att": "6.8",
        "def_air_yds": "1690",
        "def_yac": "1702",
        "blitzes": "94",
        "blitz_pct": "17.7%",
        "qb_hurry": "41",
        "qb_hurry_pct": "7.7%",
        "qb_knockdown": "47",
        "qb_knockdown_pct": "9.8%",
        "sacks": "32",
        "pressures": "120",
        "pressures_pct": "22.6%",
        "tackles_missed": "68"
    },
    {
        "g": "14",
        "pass_att_opp": "428",
        "pass_cmp_opp": "292",
        "pass_yds_opp": "2985",
        "pass_td_opp": "27",
        "def_tgt_yds_per_att": "7.4",
        "def_air_yds": "1632",
        "def_yac": "1428",
        "blitzes": "137",
        "blitz_pct": "28.7%",
        "qb_hurry": "24",
        "qb_hurry_pct": "5.0%",
        "qb_knockdown": "24",
        "qb_knockdown_pct": "5.6%",
        "sacks": "26",
        "pressures": "74",
        "pressures_pct": "15.5%",
        "tackles_missed": "101"
    },
    {
        "g": "14",
        "pass_att_opp": "423",
        "pass_cmp_opp": "268",
        "pass_yds_opp": "3049",
        "pass_td_opp": "14",
        "def_tgt_yds_per_att": "8.3",
        "def_air_yds": "1717",
        "def_yac": "1541",
        "blitzes": "110",
        "blitz_pct": "23.1%",
        "qb_hurry": "40",
        "qb_hurry_pct": "8.4%",
        "qb_knockdown": "50",
        "qb_knockdown_pct": "11.8%",
        "sacks": "33",
        "pressures": "123",
        "pressures_pct": "25.8%",
        "tackles_missed": "76"
    },
    {
        "g": "14",
        "pass_att_opp": "477",
        "pass_cmp_opp": "311",
        "pass_yds_opp": "3349",
        "pass_td_opp": "26",
        "def_tgt_yds_per_att": "7.7",
        "def_air_yds": "1762",
        "def_yac": "1652",
        "blitzes": "129",
        "blitz_pct": "24.1%",
        "qb_hurry": "41",
        "qb_hurry_pct": "7.6%",
        "qb_knockdown": "55",
        "qb_knockdown_pct": "11.5%",
        "sacks": "25",
        "pressures": "121",
        "pressures_pct": "22.6%",
        "tackles_missed": "100"
    },
    {
        "g": "14",
        "pass_att_opp": "423",
        "pass_cmp_opp": "255",
        "pass_yds_opp": "2978",
        "pass_td_opp": "20",
        "def_tgt_yds_per_att": "9.6",
        "def_air_yds": "1599",
        "def_yac": "1556",
        "blitzes": "135",
        "blitz_pct": "28.4%",
        "qb_hurry": "44",
        "qb_hurry_pct": "9.3%",
        "qb_knockdown": "55",
        "qb_knockdown_pct": "13.0%",
        "sacks": "33",
        "pressures": "132",
        "pressures_pct": "27.8%",
        "tackles_missed": "83"
    },
    {
        "g": "14",
        "pass_att_opp": "456",
        "pass_cmp_opp": "318",
        "pass_yds_opp": "3142",
        "pass_td_opp": "20",
        "def_tgt_yds_per_att": "7.2",
        "def_air_yds": "1725",
        "def_yac": "1631",
        "blitzes": "95",
        "blitz_pct": "18.4%",
        "qb_hurry": "46",
        "qb_hurry_pct": "8.9%",
        "qb_knockdown": "37",
        "qb_knockdown_pct": "8.1%",
        "sacks": "33",
        "pressures": "116",
        "pressures_pct": "22.5%",
        "tackles_missed": "118"
    },
    {
        "g": "14",
        "pass_att_opp": "438",
        "pass_cmp_opp": "307",
        "pass_yds_opp": "3038",
        "pass_td_opp": "16",
        "def_tgt_yds_per_att": "7.0",
        "def_air_yds": "1563",
        "def_yac": "1689",
        "blitzes": "102",
        "blitz_pct": "20.2%",
        "qb_hurry": "26",
        "qb_hurry_pct": "5.1%",
        "qb_knockdown": "30",
        "qb_knockdown_pct": "6.8%",
        "sacks": "36",
        "pressures": "92",
        "pressures_pct": "18.2%",
        "tackles_missed": "86"
    },
    {
        "g": "14",
        "pass_att_opp": "419",
        "pass_cmp_opp": "284",
        "pass_yds_opp": "3079",
        "pass_td_opp": "21",
        "def_tgt_yds_per_att": "8.0",
        "def_air_yds": "1510",
        "def_yac": "1835",
        "blitzes": "142",
        "blitz_pct": "29.0%",
        "qb_hurry": "49",
        "qb_hurry_pct": "10.0%",
        "qb_knockdown": "51",
        "qb_knockdown_pct": "12.2%",
        "sacks": "42",
        "pressures": "142",
        "pressures_pct": "29.0%",
        "tackles_missed": "73"
    },
    {
        "g": "14",
        "pass_att_opp": "509",
        "pass_cmp_opp": "321",
        "pass_yds_opp": "3034",
        "pass_td_opp": "17",
        "def_tgt_yds_per_att": "7.1",
        "def_air_yds": "1672",
        "def_yac": "1646",
        "blitzes": "180",
        "blitz_pct": "30.7%",
        "qb_hurry": "59",
        "qb_hurry_pct": "10.1%",
        "qb_knockdown": "57",
        "qb_knockdown_pct": "11.2%",
        "sacks": "49",
        "pressures": "165",
        "pressures_pct": "28.2%",
        "tackles_missed": "72"
    },
    {
        "g": "14",
        "pass_att_opp": "489",
        "pass_cmp_opp": "299",
        "pass_yds_opp": "3283",
        "pass_td_opp": "13",
        "def_tgt_yds_per_att": "9.2",
        "def_air_yds": "1973",
        "def_yac": "1484",
        "blitzes": "178",
        "blitz_pct": "32.4%",
        "qb_hurry": "58",
        "qb_hurry_pct": "10.6%",
        "qb_knockdown": "54",
        "qb_knockdown_pct": "11.0%",
        "sacks": "31",
        "pressures": "143",
        "pressures_pct": "26.0%",
        "tackles_missed": "71"
    },
    {
        "g": "14",
        "pass_att_opp": "462",
        "pass_cmp_opp": "312",
        "pass_yds_opp": "3016",
        "pass_td_opp": "19",
        "def_tgt_yds_per_att": "7.4",
        "def_air_yds": "1723",
        "def_yac": "1520",
        "blitzes": "96",
        "blitz_pct": "18.1%",
        "qb_hurry": "45",
        "qb_hurry_pct": "8.5%",
        "qb_knockdown": "36",
        "qb_knockdown_pct": "7.8%",
        "sacks": "40",
        "pressures": "121",
        "pressures_pct": "22.8%",
        "tackles_missed": "91"
    },
    {
        "g": "14",
        "pass_att_opp": "470",
        "pass_cmp_opp": "271",
        "pass_yds_opp": "2756",
        "pass_td_opp": "27",
        "def_tgt_yds_per_att": "9.1",
        "def_air_yds": "1445",
        "def_yac": "1549",
        "blitzes": "124",
        "blitz_pct": "23.0%",
        "qb_hurry": "43",
        "qb_hurry_pct": "8.0%",
        "qb_knockdown": "41",
        "qb_knockdown_pct": "8.7%",
        "sacks": "45",
        "pressures": "129",
        "pressures_pct": "23.9%",
        "tackles_missed": "100"
    },
    {
        "g": "14",
        "pass_att_opp": "471",
        "pass_cmp_opp": "323",
        "pass_yds_opp": "3700",
        "pass_td_opp": "27",
        "def_tgt_yds_per_att": "7.8",
        "def_air_yds": "1893",
        "def_yac": "1898",
        "blitzes": "75",
        "blitz_pct": "14.0%",
        "qb_hurry": "38",
        "qb_hurry_pct": "7.1%",
        "qb_knockdown": "27",
        "qb_knockdown_pct": "5.7%",
        "sacks": "26",
        "pressures": "91",
        "pressures_pct": "17.0%",
        "tackles_missed": "79"
    },
    {
        "g": "14",
        "pass_att_opp": "464",
        "pass_cmp_opp": "303",
        "pass_yds_opp": "3010",
        "pass_td_opp": "18",
        "def_tgt_yds_per_att": "7.7",
        "def_air_yds": "1555",
        "def_yac": "1572",
        "blitzes": "178",
        "blitz_pct": "33.4%",
        "qb_hurry": "49",
        "qb_hurry_pct": "9.2%",
        "qb_knockdown": "59",
        "qb_knockdown_pct": "12.7%",
        "sacks": "32",
        "pressures": "140",
        "pressures_pct": "26.3%",
        "tackles_missed": "80"
    },
    {
        "g": "14",
        "pass_att_opp": "448",
        "pass_cmp_opp": "292",
        "pass_yds_opp": "2870",
        "pass_td_opp": "16",
        "def_tgt_yds_per_att": "6.6",
        "def_air_yds": "1482",
        "def_yac": "1552",
        "blitzes": "119",
        "blitz_pct": "24.0%",
        "qb_hurry": "45",
        "qb_hurry_pct": "9.1%",
        "qb_knockdown": "34",
        "qb_knockdown_pct": "7.6%",
        "sacks": "28",
        "pressures": "107",
        "pressures_pct": "21.6%",
        "tackles_missed": "86"
    },
    {
        "g": "14",
        "pass_att_opp": "531",
        "pass_cmp_opp": "338",
        "pass_yds_opp": "3429",
        "pass_td_opp": "19",
        "def_tgt_yds_per_att": "7.7",
        "def_air_yds": "2041",
        "def_yac": "1672",
        "blitzes": "232",
        "blitz_pct": "38.9%",
        "qb_hurry": "60",
        "qb_hurry_pct": "10.1%",
        "qb_knockdown": "55",
        "qb_knockdown_pct": "10.4%",
        "sacks": "42",
        "pressures": "157",
        "pressures_pct": "26.3%",
        "tackles_missed": "67"
    },
    {
        "g": "14",
        "pass_att_opp": "494",
        "pass_cmp_opp": "308",
        "pass_yds_opp": "3391",
        "pass_td_opp": "14",
        "def_tgt_yds_per_att": "8.4",
        "def_air_yds": "1695",
        "def_yac": "1910",
        "blitzes": "108",
        "blitz_pct": "19.0%",
        "qb_hurry": "51",
        "qb_hurry_pct": "9.0%",
        "qb_knockdown": "39",
        "qb_knockdown_pct": "7.9%",
        "sacks": "37",
        "pressures": "127",
        "pressures_pct": "22.4%",
        "tackles_missed": "97"
    },
    {
        "g": "14",
        "pass_att_opp": "432",
        "pass_cmp_opp": "286",
        "pass_yds_opp": "3034",
        "pass_td_opp": "22",
        "def_tgt_yds_per_att": "8.6",
        "def_air_yds": "1793",
        "def_yac": "1358",
        "blitzes": "121",
        "blitz_pct": "25.2%",
        "qb_hurry": "32",
        "qb_hurry_pct": "6.7%",
        "qb_knockdown": "27",
        "qb_knockdown_pct": "6.3%",
        "sacks": "27",
        "pressures": "86",
        "pressures_pct": "17.9%",
        "tackles_missed": "58"
    },
    {
        "g": "14",
        "pass_att_opp": "397",
        "pass_cmp_opp": "278",
        "pass_yds_opp": "2806",
        "pass_td_opp": "19",
        "def_tgt_yds_per_att": "7.1",
        "def_air_yds": "1665",
        "def_yac": "1403",
        "blitzes": "128",
        "blitz_pct": "27.5%",
        "qb_hurry": "35",
        "qb_hurry_pct": "7.5%",
        "qb_knockdown": "33",
        "qb_knockdown_pct": "8.3%",
        "sacks": "41",
        "pressures": "109",
        "pressures_pct": "23.4%",
        "tackles_missed": "95"
    },
    {
        "g": "14",
        "pass_att_opp": "433",
        "pass_cmp_opp": "271",
        "pass_yds_opp": "2715",
        "pass_td_opp": "13",
        "def_tgt_yds_per_att": "8.6",
        "def_air_yds": "1617",
        "def_yac": "1383",
        "blitzes": "128",
        "blitz_pct": "25.5%",
        "qb_hurry": "49",
        "qb_hurry_pct": "9.8%",
        "qb_knockdown": "31",
        "qb_knockdown_pct": "7.2%",
        "sacks": "39",
        "pressures": "119",
        "pressures_pct": "23.8%",
        "tackles_missed": "107"
    },
    {
        "g": "14",
        "pass_att_opp": "412",
        "pass_cmp_opp": "274",
        "pass_yds_opp": "2551",
        "pass_td_opp": "23",
        "def_tgt_yds_per_att": "7.1",
        "def_air_yds": "1268",
        "def_yac": "1432",
        "blitzes": "96",
        "blitz_pct": "20.2%",
        "qb_hurry": "26",
        "qb_hurry_pct": "5.5%",
        "qb_knockdown": "30",
        "qb_knockdown_pct": "7.3%",
        "sacks": "28",
        "pressures": "84",
        "pressures_pct": "17.6%",
        "tackles_missed": "77"
    },
    {
        "g": "14",
        "pass_att_opp": "445",
        "pass_cmp_opp": "275",
        "pass_yds_opp": "2427",
        "pass_td_opp": "15",
        "def_tgt_yds_per_att": "7.6",
        "def_air_yds": "1414",
        "def_yac": "1292",
        "blitzes": "92",
        "blitz_pct": "17.9%",
        "qb_hurry": "22",
        "qb_hurry_pct": "4.3%",
        "qb_knockdown": "37",
        "qb_knockdown_pct": "8.3%",
        "sacks": "39",
        "pressures": "98",
        "pressures_pct": "19.1%",
        "tackles_missed": "78"
    },
    {
        "g": "14",
        "pass_att_opp": "475",
        "pass_cmp_opp": "301",
        "pass_yds_opp": "3112",
        "pass_td_opp": "16",
        "def_tgt_yds_per_att": "7.5",
        "def_air_yds": "1752",
        "def_yac": "1595",
        "blitzes": "128",
        "blitz_pct": "24.5%",
        "qb_hurry": "29",
        "qb_hurry_pct": "5.5%",
        "qb_knockdown": "60",
        "qb_knockdown_pct": "12.6%",
        "sacks": "35",
        "pressures": "124",
        "pressures_pct": "23.7%",
        "tackles_missed": "58"
    },
    {
        "g": "14",
        "pass_att_opp": "450",
        "pass_cmp_opp": "297",
        "pass_yds_opp": "2916",
        "pass_td_opp": "25",
        "def_tgt_yds_per_att": "6.9",
        "def_air_yds": "1547",
        "def_yac": "1589",
        "blitzes": "144",
        "blitz_pct": "28.4%",
        "qb_hurry": "41",
        "qb_hurry_pct": "8.1%",
        "qb_knockdown": "35",
        "qb_knockdown_pct": "7.8%",
        "sacks": "32",
        "pressures": "108",
        "pressures_pct": "21.3%",
        "tackles_missed": "116"
    },
    {
        "g": "14",
        "pass_att_opp": "425",
        "pass_cmp_opp": "273",
        "pass_yds_opp": "3054",
        "pass_td_opp": "23",
        "def_tgt_yds_per_att": "7.9",
        "def_air_yds": "1701",
        "def_yac": "1600",
        "blitzes": "114",
        "blitz_pct": "23.6%",
        "qb_hurry": "49",
        "qb_hurry_pct": "10.1%",
        "qb_knockdown": "31",
        "qb_knockdown_pct": "7.3%",
        "sacks": "31",
        "pressures": "111",
        "pressures_pct": "22.9%",
        "tackles_missed": "105"
    },
    {
        "g": "14",
        "pass_att_opp": "526",
        "pass_cmp_opp": "338",
        "pass_yds_opp": "3625",
        "pass_td_opp": "24",
        "def_tgt_yds_per_att": "8.2",
        "def_air_yds": "2182",
        "def_yac": "1589",
        "blitzes": "128",
        "blitz_pct": "21.6%",
        "qb_hurry": "43",
        "qb_hurry_pct": "7.3%",
        "qb_knockdown": "53",
        "qb_knockdown_pct": "10.1%",
        "sacks": "44",
        "pressures": "140",
        "pressures_pct": "23.6%",
        "tackles_missed": "65"
    },
    {
        "g": "14",
        "pass_att_opp": "465",
        "pass_cmp_opp": "300",
        "pass_yds_opp": "2962",
        "pass_td_opp": "19",
        "def_tgt_yds_per_att": "7.6",
        "def_air_yds": "1743",
        "def_yac": "1387",
        "blitzes": "126",
        "blitz_pct": "23.5%",
        "qb_hurry": "28",
        "qb_hurry_pct": "5.2%",
        "qb_knockdown": "40",
        "qb_knockdown_pct": "8.6%",
        "sacks": "40",
        "pressures": "108",
        "pressures_pct": "20.1%",
        "tackles_missed": "87"
    },
    {
        "g": "14",
        "pass_att_opp": "465",
        "pass_cmp_opp": "306",
        "pass_yds_opp": "2991",
        "pass_td_opp": "21",
        "def_tgt_yds_per_att": "6.7",
        "def_air_yds": "1507",
        "def_yac": "1708",
        "blitzes": "122",
        "blitz_pct": "23.4%",
        "qb_hurry": "42",
        "qb_hurry_pct": "8.0%",
        "qb_knockdown": "55",
        "qb_knockdown_pct": "11.8%",
        "sacks": "32",
        "pressures": "129",
        "pressures_pct": "24.7%",
        "tackles_missed": "87"
    },
    {
        "g": "14",
        "pass_att_opp": "413",
        "pass_cmp_opp": "265",
        "pass_yds_opp": "2534",
        "pass_td_opp": "17",
        "def_tgt_yds_per_att": "7.7",
        "def_air_yds": "1307",
        "def_yac": "1409",
        "blitzes": "79",
        "blitz_pct": "17.0%",
        "qb_hurry": "30",
        "qb_hurry_pct": "6.5%",
        "qb_knockdown": "38",
        "qb_knockdown_pct": "9.2%",
        "sacks": "35",
        "pressures": "103",
        "pressures_pct": "22.2%",
        "tackles_missed": "84"
    },
    {
        "g": "14",
        "pass_att_opp": "525",
        "pass_cmp_opp": "351",
        "pass_yds_opp": "3468",
        "pass_td_opp": "23",
        "def_tgt_yds_per_att": "7.6",
        "def_air_yds": "1950",
        "def_yac": "1781",
        "blitzes": "195",
        "blitz_pct": "32.7%",
        "qb_hurry": "36",
        "qb_hurry_pct": "6.0%",
        "qb_knockdown": "59",
        "qb_knockdown_pct": "11.2%",
        "sacks": "38",
        "pressures": "133",
        "pressures_pct": "22.3%",
        "tackles_missed": "89"
    },
    {
        "g": "14",
        "pass_att_opp": "399",
        "pass_cmp_opp": "253",
        "pass_yds_opp": "2655",
        "pass_td_opp": "23",
        "def_tgt_yds_per_att": "8.2",
        "def_air_yds": "1580",
        "def_yac": "1291",
        "blitzes": "136",
        "blitz_pct": "29.6%",
        "qb_hurry": "36",
        "qb_hurry_pct": "7.8%",
        "qb_knockdown": "37",
        "qb_knockdown_pct": "9.3%",
        "sacks": "35",
        "pressures": "108",
        "pressures_pct": "23.5%",
        "tackles_missed": "70"
    }
]

module.exports.defenseStats = defenseStats;
module.exports.advancedDefenseStats = advancedDefenseStats;
