const defenseStats = [
            {
                "team": "Green Bay Packers",
                "g": "3",
                "points": "44",
                "total_yards": "697",
                "plays_offense": "187",
                "yds_per_play_offense": "3.7",
                "turnovers": "2",
                "fumbles_lost": "0",
                "first_down": "46",
                "pass_cmp": "76",
                "pass_att": "117",
                "pass_yds": "504",
                "pass_td": "3",
                "pass_int": "2",
                "pass_net_yds_per_att": "4.0",
                "pass_fd": "30",
                "rush_att": "60",
                "rush_yds": "193",
                "rush_td": "1",
                "rush_yds_per_att": "3.2",
                "rush_fd": "10",
                "penalties": "20",
                "penalties_yds": "160",
                "pen_fd": "6",
                "score_pct": "30.0",
                "turnover_pct": "6.7",
                "exp_pts_def_tot": "19.44"
            },
            {
                "team": "San Francisco 49ers",
                "g": "3",
                "points": "49",
                "total_yards": "797",
                "plays_offense": "181",
                "yds_per_play_offense": "4.4",
                "turnovers": "3",
                "fumbles_lost": "3",
                "first_down": "51",
                "pass_cmp": "63",
                "pass_att": "92",
                "pass_yds": "486",
                "pass_td": "4",
                "pass_int": "0",
                "pass_net_yds_per_att": "5.0",
                "pass_fd": "26",
                "rush_att": "84",
                "rush_yds": "311",
                "rush_td": "1",
                "rush_yds_per_att": "3.7",
                "rush_fd": "19",
                "penalties": "16",
                "penalties_yds": "105",
                "pen_fd": "6",
                "score_pct": "29.0",
                "turnover_pct": "9.7",
                "exp_pts_def_tot": "-0.11"
            },
            {
                "team": "Los Angeles Chargers",
                "g": "3",
                "points": "50",
                "total_yards": "830",
                "plays_offense": "171",
                "yds_per_play_offense": "4.9",
                "turnovers": "3",
                "fumbles_lost": "0",
                "first_down": "42",
                "pass_cmp": "62",
                "pass_att": "107",
                "pass_yds": "546",
                "pass_td": "2",
                "pass_int": "3",
                "pass_net_yds_per_att": "4.8",
                "pass_fd": "22",
                "rush_att": "57",
                "rush_yds": "284",
                "rush_td": "2",
                "rush_yds_per_att": "5.0",
                "rush_fd": "16",
                "penalties": "25",
                "penalties_yds": "208",
                "pen_fd": "4",
                "score_pct": "40.0",
                "turnover_pct": "10.0",
                "exp_pts_def_tot": "10.68"
            },
            {
                "team": "Jacksonville Jaguars",
                "g": "3",
                "points": "51",
                "total_yards": "876",
                "plays_offense": "185",
                "yds_per_play_offense": "4.7",
                "turnovers": "9",
                "fumbles_lost": "2",
                "first_down": "52",
                "pass_cmp": "71",
                "pass_att": "118",
                "pass_yds": "628",
                "pass_td": "5",
                "pass_int": "7",
                "pass_net_yds_per_att": "5.1",
                "pass_fd": "33",
                "rush_att": "61",
                "rush_yds": "248",
                "rush_td": "1",
                "rush_yds_per_att": "4.1",
                "rush_fd": "12",
                "penalties": "14",
                "penalties_yds": "130",
                "pen_fd": "7",
                "score_pct": "26.5",
                "turnover_pct": "26.5",
                "exp_pts_def_tot": "15.02"
            },
            {
                "team": "Houston Texans",
                "g": "3",
                "points": "51",
                "total_yards": "947",
                "plays_offense": "195",
                "yds_per_play_offense": "4.9",
                "turnovers": "2",
                "fumbles_lost": "1",
                "first_down": "60",
                "pass_cmp": "66",
                "pass_att": "107",
                "pass_yds": "620",
                "pass_td": "3",
                "pass_int": "1",
                "pass_net_yds_per_att": "5.3",
                "pass_fd": "35",
                "rush_att": "79",
                "rush_yds": "327",
                "rush_td": "4",
                "rush_yds_per_att": "4.1",
                "rush_fd": "17",
                "penalties": "23",
                "penalties_yds": "175",
                "pen_fd": "8",
                "score_pct": "25.0",
                "turnover_pct": "6.3",
                "exp_pts_def_tot": "-7.26"
            },
            {
                "team": "Carolina Panthers",
                "g": "3",
                "points": "53",
                "total_yards": "1003",
                "plays_offense": "177",
                "yds_per_play_offense": "5.7",
                "turnovers": "5",
                "fumbles_lost": "1",
                "first_down": "52",
                "pass_cmp": "59",
                "pass_att": "99",
                "pass_yds": "590",
                "pass_td": "2",
                "pass_int": "4",
                "pass_net_yds_per_att": "5.9",
                "pass_fd": "30",
                "rush_att": "77",
                "rush_yds": "413",
                "rush_td": "2",
                "rush_yds_per_att": "5.4",
                "rush_fd": "21",
                "penalties": "26",
                "penalties_yds": "212",
                "pen_fd": "1",
                "score_pct": "34.5",
                "turnover_pct": "17.2",
                "exp_pts_def_tot": "1.34"
            },
            {
                "team": "Minnesota Vikings",
                "g": "3",
                "points": "56",
                "total_yards": "814",
                "plays_offense": "178",
                "yds_per_play_offense": "4.6",
                "turnovers": "7",
                "fumbles_lost": "5",
                "first_down": "51",
                "pass_cmp": "53",
                "pass_att": "83",
                "pass_yds": "424",
                "pass_td": "2",
                "pass_int": "2",
                "pass_net_yds_per_att": "4.6",
                "pass_fd": "21",
                "rush_att": "86",
                "rush_yds": "390",
                "rush_td": "2",
                "rush_yds_per_att": "4.5",
                "rush_fd": "22",
                "penalties": "21",
                "penalties_yds": "201",
                "pen_fd": "8",
                "score_pct": "30.6",
                "turnover_pct": "19.4",
                "exp_pts_def_tot": "36.82"
            },
            {
                "team": "Kansas City Chiefs",
                "g": "3",
                "points": "56",
                "total_yards": "891",
                "plays_offense": "181",
                "yds_per_play_offense": "4.9",
                "turnovers": "2",
                "fumbles_lost": "0",
                "first_down": "57",
                "pass_cmp": "58",
                "pass_att": "88",
                "pass_yds": "549",
                "pass_td": "3",
                "pass_int": "2",
                "pass_net_yds_per_att": "5.8",
                "pass_fd": "27",
                "rush_att": "86",
                "rush_yds": "342",
                "rush_td": "3",
                "rush_yds_per_att": "4.0",
                "rush_fd": "23",
                "penalties": "19",
                "penalties_yds": "179",
                "pen_fd": "7",
                "score_pct": "40.7",
                "turnover_pct": "7.4",
                "exp_pts_def_tot": "-5.43"
            },
            {
                "team": "Indianapolis Colts",
                "g": "3",
                "points": "56",
                "total_yards": "817",
                "plays_offense": "165",
                "yds_per_play_offense": "5.0",
                "turnovers": "5",
                "fumbles_lost": "1",
                "first_down": "56",
                "pass_cmp": "64",
                "pass_att": "99",
                "pass_yds": "535",
                "pass_td": "5",
                "pass_int": "4",
                "pass_net_yds_per_att": "5.0",
                "pass_fd": "31",
                "rush_att": "59",
                "rush_yds": "282",
                "rush_td": "2",
                "rush_yds_per_att": "4.8",
                "rush_fd": "18",
                "penalties": "19",
                "penalties_yds": "166",
                "pen_fd": "7",
                "score_pct": "36.0",
                "turnover_pct": "20.0",
                "exp_pts_def_tot": "-8.25"
            },
            {
                "team": "Washington Commanders",
                "g": "3",
                "points": "57",
                "total_yards": "989",
                "plays_offense": "187",
                "yds_per_play_offense": "5.3",
                "turnovers": "",
                "fumbles_lost": "0",
                "first_down": "56",
                "pass_cmp": "55",
                "pass_att": "97",
                "pass_yds": "687",
                "pass_td": "5",
                "pass_int": "0",
                "pass_net_yds_per_att": "6.5",
                "pass_fd": "35",
                "rush_att": "81",
                "rush_yds": "302",
                "rush_td": "1",
                "rush_yds_per_att": "3.7",
                "rush_fd": "15",
                "penalties": "22",
                "penalties_yds": "166",
                "pen_fd": "6",
                "score_pct": "33.3",
                "turnover_pct": "0.0",
                "exp_pts_def_tot": "-3.80"
            },
            {
                "team": "Atlanta Falcons",
                "g": "3",
                "points": "59",
                "total_yards": "682",
                "plays_offense": "157",
                "yds_per_play_offense": "4.3",
                "turnovers": "5",
                "fumbles_lost": "3",
                "first_down": "41",
                "pass_cmp": "44",
                "pass_att": "77",
                "pass_yds": "393",
                "pass_td": "3",
                "pass_int": "2",
                "pass_net_yds_per_att": "4.6",
                "pass_fd": "24",
                "rush_att": "72",
                "rush_yds": "289",
                "rush_td": "2",
                "rush_yds_per_att": "4.0",
                "rush_fd": "15",
                "penalties": "19",
                "penalties_yds": "165",
                "pen_fd": "2",
                "score_pct": "37.9",
                "turnover_pct": "10.3",
                "exp_pts_def_tot": "4.75"
            },
            {
                "team": "Los Angeles Rams",
                "g": "3",
                "points": "61",
                "total_yards": "805",
                "plays_offense": "184",
                "yds_per_play_offense": "4.4",
                "turnovers": "4",
                "fumbles_lost": "3",
                "first_down": "55",
                "pass_cmp": "59",
                "pass_att": "92",
                "pass_yds": "496",
                "pass_td": "4",
                "pass_int": "1",
                "pass_net_yds_per_att": "4.8",
                "pass_fd": "26",
                "rush_att": "80",
                "rush_yds": "309",
                "rush_td": "1",
                "rush_yds_per_att": "3.9",
                "rush_fd": "23",
                "penalties": "26",
                "penalties_yds": "192",
                "pen_fd": "6",
                "score_pct": "36.7",
                "turnover_pct": "13.3",
                "exp_pts_def_tot": "6.14"
            },
            {
                "team": "Philadelphia Eagles",
                "g": "3",
                "points": "63",
                "total_yards": "957",
                "plays_offense": "179",
                "yds_per_play_offense": "5.3",
                "turnovers": "3",
                "fumbles_lost": "1",
                "first_down": "61",
                "pass_cmp": "56",
                "pass_att": "97",
                "pass_yds": "557",
                "pass_td": "3",
                "pass_int": "2",
                "pass_net_yds_per_att": "5.6",
                "pass_fd": "26",
                "rush_att": "79",
                "rush_yds": "400",
                "rush_td": "3",
                "rush_yds_per_att": "5.1",
                "rush_fd": "27",
                "penalties": "14",
                "penalties_yds": "128",
                "pen_fd": "8",
                "score_pct": "46.4",
                "turnover_pct": "10.7",
                "exp_pts_def_tot": "-13.44"
            },
            {
                "team": "Denver Broncos",
                "g": "3",
                "points": "64",
                "total_yards": "982",
                "plays_offense": "202",
                "yds_per_play_offense": "4.9",
                "turnovers": "4",
                "fumbles_lost": "3",
                "first_down": "62",
                "pass_cmp": "63",
                "pass_att": "109",
                "pass_yds": "638",
                "pass_td": "2",
                "pass_int": "1",
                "pass_net_yds_per_att": "5.3",
                "pass_fd": "38",
                "rush_att": "81",
                "rush_yds": "344",
                "rush_td": "2",
                "rush_yds_per_att": "4.2",
                "rush_fd": "14",
                "penalties": "27",
                "penalties_yds": "224",
                "pen_fd": "10",
                "score_pct": "45.7",
                "turnover_pct": "8.6",
                "exp_pts_def_tot": "3.31"
            },
            {
                "team": "Tampa Bay Buccaneers",
                "g": "3",
                "points": "66",
                "total_yards": "891",
                "plays_offense": "180",
                "yds_per_play_offense": "5.0",
                "turnovers": "2",
                "fumbles_lost": "1",
                "first_down": "56",
                "pass_cmp": "66",
                "pass_att": "102",
                "pass_yds": "639",
                "pass_td": "4",
                "pass_int": "1",
                "pass_net_yds_per_att": "5.8",
                "pass_fd": "36",
                "rush_att": "70",
                "rush_yds": "252",
                "rush_td": "2",
                "rush_yds_per_att": "3.6",
                "rush_fd": "12",
                "penalties": "21",
                "penalties_yds": "181",
                "pen_fd": "8",
                "score_pct": "38.7",
                "turnover_pct": "6.5",
                "exp_pts_def_tot": "1.10"
            },
            {
                "team": "Seattle Seahawks",
                "g": "4",
                "points": "67",
                "total_yards": "1188",
                "plays_offense": "265",
                "yds_per_play_offense": "4.5",
                "turnovers": "7",
                "fumbles_lost": "0",
                "first_down": "76",
                "pass_cmp": "101",
                "pass_att": "152",
                "pass_yds": "829",
                "pass_td": "6",
                "pass_int": "7",
                "pass_net_yds_per_att": "5.1",
                "pass_fd": "46",
                "rush_att": "101",
                "rush_yds": "359",
                "rush_td": "0",
                "rush_yds_per_att": "3.6",
                "rush_fd": "19",
                "penalties": "29",
                "penalties_yds": "199",
                "pen_fd": "11",
                "score_pct": "30.4",
                "turnover_pct": "15.2",
                "exp_pts_def_tot": "2.92"
            },
            {
                "team": "Cleveland Browns",
                "g": "3",
                "points": "68",
                "total_yards": "613",
                "plays_offense": "163",
                "yds_per_play_offense": "3.8",
                "turnovers": "1",
                "fumbles_lost": "0",
                "first_down": "39",
                "pass_cmp": "51",
                "pass_att": "77",
                "pass_yds": "441",
                "pass_td": "6",
                "pass_int": "1",
                "pass_net_yds_per_att": "5.0",
                "pass_fd": "25",
                "rush_att": "75",
                "rush_yds": "172",
                "rush_td": "1",
                "rush_yds_per_att": "2.3",
                "rush_fd": "9",
                "penalties": "27",
                "penalties_yds": "136",
                "pen_fd": "5",
                "score_pct": "34.4",
                "turnover_pct": "3.1",
                "exp_pts_def_tot": "8.06"
            },
            {
                "team": "New England Patriots",
                "g": "3",
                "points": "68",
                "total_yards": "950",
                "plays_offense": "163",
                "yds_per_play_offense": "5.8",
                "turnovers": "3",
                "fumbles_lost": "0",
                "first_down": "54",
                "pass_cmp": "66",
                "pass_att": "89",
                "pass_yds": "769",
                "pass_td": "5",
                "pass_int": "3",
                "pass_net_yds_per_att": "7.8",
                "pass_fd": "37",
                "rush_att": "65",
                "rush_yds": "181",
                "rush_td": "2",
                "rush_yds_per_att": "2.8",
                "rush_fd": "11",
                "penalties": "27",
                "penalties_yds": "201",
                "pen_fd": "6",
                "score_pct": "36.7",
                "turnover_pct": "10.0",
                "exp_pts_def_tot": "-15.09"
            },
            {
                "team": "Buffalo Bills",
                "g": "3",
                "points": "71",
                "total_yards": "862",
                "plays_offense": "156",
                "yds_per_play_offense": "5.5",
                "turnovers": "3",
                "fumbles_lost": "2",
                "first_down": "49",
                "pass_cmp": "46",
                "pass_att": "75",
                "pass_yds": "394",
                "pass_td": "5",
                "pass_int": "1",
                "pass_net_yds_per_att": "4.9",
                "pass_fd": "24",
                "rush_att": "75",
                "rush_yds": "468",
                "rush_td": "4",
                "rush_yds_per_att": "6.2",
                "rush_fd": "23",
                "penalties": "18",
                "penalties_yds": "143",
                "pen_fd": "2",
                "score_pct": "40.0",
                "turnover_pct": "10.0",
                "exp_pts_def_tot": "-16.60"
            },
            {
                "team": "Las Vegas Raiders",
                "g": "3",
                "points": "74",
                "total_yards": "1053",
                "plays_offense": "177",
                "yds_per_play_offense": "5.9",
                "turnovers": "3",
                "fumbles_lost": "2",
                "first_down": "50",
                "pass_cmp": "64",
                "pass_att": "94",
                "pass_yds": "711",
                "pass_td": "4",
                "pass_int": "1",
                "pass_net_yds_per_att": "7.0",
                "pass_fd": "30",
                "rush_att": "76",
                "rush_yds": "342",
                "rush_td": "3",
                "rush_yds_per_att": "4.5",
                "rush_fd": "16",
                "penalties": "21",
                "penalties_yds": "157",
                "pen_fd": "4",
                "score_pct": "39.4",
                "turnover_pct": "9.1",
                "exp_pts_def_tot": "-17.58"
            },
            {
                "team": "Arizona Cardinals",
                "g": "4",
                "points": "74",
                "total_yards": "1406",
                "plays_offense": "272",
                "yds_per_play_offense": "5.2",
                "turnovers": "4",
                "fumbles_lost": "2",
                "first_down": "86",
                "pass_cmp": "107",
                "pass_att": "168",
                "pass_yds": "1022",
                "pass_td": "5",
                "pass_int": "2",
                "pass_net_yds_per_att": "5.8",
                "pass_fd": "56",
                "rush_att": "96",
                "rush_yds": "384",
                "rush_td": "2",
                "rush_yds_per_att": "4.0",
                "rush_fd": "19",
                "penalties": "31",
                "penalties_yds": "315",
                "pen_fd": "11",
                "score_pct": "40.0",
                "turnover_pct": "7.5",
                "exp_pts_def_tot": "-10.68"
            },
            {
                "team": "Pittsburgh Steelers",
                "g": "3",
                "points": "77",
                "total_yards": "1158",
                "plays_offense": "197",
                "yds_per_play_offense": "5.9",
                "turnovers": "8",
                "fumbles_lost": "5",
                "first_down": "70",
                "pass_cmp": "66",
                "pass_att": "92",
                "pass_yds": "740",
                "pass_td": "5",
                "pass_int": "3",
                "pass_net_yds_per_att": "7.4",
                "pass_fd": "35",
                "rush_att": "97",
                "rush_yds": "418",
                "rush_td": "4",
                "rush_yds_per_att": "4.3",
                "rush_fd": "31",
                "penalties": "16",
                "penalties_yds": "138",
                "pen_fd": "4",
                "score_pct": "40.0",
                "turnover_pct": "23.3",
                "exp_pts_def_tot": "-13.61"
            },
            {
                "team": "Detroit Lions",
                "g": "3",
                "points": "78",
                "total_yards": "923",
                "plays_offense": "165",
                "yds_per_play_offense": "5.6",
                "turnovers": "3",
                "fumbles_lost": "2",
                "first_down": "54",
                "pass_cmp": "58",
                "pass_att": "83",
                "pass_yds": "626",
                "pass_td": "7",
                "pass_int": "1",
                "pass_net_yds_per_att": "6.7",
                "pass_fd": "33",
                "rush_att": "71",
                "rush_yds": "297",
                "rush_td": "3",
                "rush_yds_per_att": "4.2",
                "rush_fd": "15",
                "penalties": "15",
                "penalties_yds": "100",
                "pen_fd": "6",
                "score_pct": "41.9",
                "turnover_pct": "9.7",
                "exp_pts_def_tot": "-18.33"
            },
            {
                "team": "New York Giants",
                "g": "3",
                "points": "83",
                "total_yards": "1216",
                "plays_offense": "215",
                "yds_per_play_offense": "5.7",
                "turnovers": "1",
                "fumbles_lost": "0",
                "first_down": "79",
                "pass_cmp": "79",
                "pass_att": "119",
                "pass_yds": "756",
                "pass_td": "4",
                "pass_int": "1",
                "pass_net_yds_per_att": "6.0",
                "pass_fd": "42",
                "rush_att": "88",
                "rush_yds": "460",
                "rush_td": "5",
                "rush_yds_per_att": "5.2",
                "rush_fd": "25",
                "penalties": "32",
                "penalties_yds": "280",
                "pen_fd": "12",
                "score_pct": "47.1",
                "turnover_pct": "2.9",
                "exp_pts_def_tot": "-48.46"
            },
            {
                "team": "New Orleans Saints",
                "g": "3",
                "points": "90",
                "total_yards": "940",
                "plays_offense": "183",
                "yds_per_play_offense": "5.1",
                "turnovers": "2",
                "fumbles_lost": "2",
                "first_down": "64",
                "pass_cmp": "63",
                "pass_att": "89",
                "pass_yds": "630",
                "pass_td": "7",
                "pass_int": "0",
                "pass_net_yds_per_att": "6.5",
                "pass_fd": "37",
                "rush_att": "86",
                "rush_yds": "310",
                "rush_td": "2",
                "rush_yds_per_att": "3.6",
                "rush_fd": "17",
                "penalties": "22",
                "penalties_yds": "164",
                "pen_fd": "10",
                "score_pct": "50.0",
                "turnover_pct": "6.7",
                "exp_pts_def_tot": "-23.89"
            },
            {
                "team": "Cincinnati Bengals",
                "g": "3",
                "points": "91",
                "total_yards": "1079",
                "plays_offense": "199",
                "yds_per_play_offense": "5.4",
                "turnovers": "4",
                "fumbles_lost": "0",
                "first_down": "65",
                "pass_cmp": "71",
                "pass_att": "111",
                "pass_yds": "722",
                "pass_td": "6",
                "pass_int": "4",
                "pass_net_yds_per_att": "6.2",
                "pass_fd": "38",
                "rush_att": "82",
                "rush_yds": "357",
                "rush_td": "3",
                "rush_yds_per_att": "4.4",
                "rush_fd": "20",
                "penalties": "26",
                "penalties_yds": "213",
                "pen_fd": "7",
                "score_pct": "41.2",
                "turnover_pct": "11.8",
                "exp_pts_def_tot": "-16.34"
            },
            {
                "team": "Dallas Cowboys",
                "g": "3",
                "points": "92",
                "total_yards": "1193",
                "plays_offense": "184",
                "yds_per_play_offense": "6.5",
                "turnovers": "1",
                "fumbles_lost": "0",
                "first_down": "61",
                "pass_cmp": "68",
                "pass_att": "92",
                "pass_yds": "864",
                "pass_td": "7",
                "pass_int": "1",
                "pass_net_yds_per_att": "9.0",
                "pass_fd": "32",
                "rush_att": "88",
                "rush_yds": "329",
                "rush_td": "4",
                "rush_yds_per_att": "3.7",
                "rush_fd": "27",
                "penalties": "29",
                "penalties_yds": "311",
                "pen_fd": "2",
                "score_pct": "53.3",
                "turnover_pct": "3.3",
                "exp_pts_def_tot": "-47.78"
            },
            {
                "team": "New York Jets",
                "g": "3",
                "points": "93",
                "total_yards": "1021",
                "plays_offense": "189",
                "yds_per_play_offense": "5.4",
                "turnovers": "",
                "fumbles_lost": "0",
                "first_down": "63",
                "pass_cmp": "56",
                "pass_att": "86",
                "pass_yds": "622",
                "pass_td": "5",
                "pass_int": "0",
                "pass_net_yds_per_att": "6.8",
                "pass_fd": "35",
                "rush_att": "97",
                "rush_yds": "399",
                "rush_td": "3",
                "rush_yds_per_att": "4.1",
                "rush_fd": "18",
                "penalties": "24",
                "penalties_yds": "219",
                "pen_fd": "10",
                "score_pct": "54.5",
                "turnover_pct": "0.0",
                "exp_pts_def_tot": "-26.50"
            },
            {
                "team": "Chicago Bears",
                "g": "3",
                "points": "93",
                "total_yards": "1161",
                "plays_offense": "174",
                "yds_per_play_offense": "6.7",
                "turnovers": "5",
                "fumbles_lost": "1",
                "first_down": "62",
                "pass_cmp": "70",
                "pass_att": "93",
                "pass_yds": "743",
                "pass_td": "8",
                "pass_int": "4",
                "pass_net_yds_per_att": "7.6",
                "pass_fd": "34",
                "rush_att": "76",
                "rush_yds": "418",
                "rush_td": "3",
                "rush_yds_per_att": "5.5",
                "rush_fd": "22",
                "penalties": "15",
                "penalties_yds": "103",
                "pen_fd": "6",
                "score_pct": "45.7",
                "turnover_pct": "14.3",
                "exp_pts_def_tot": "-25.58"
            },
            {
                "team": "Tennessee Titans",
                "g": "3",
                "points": "94",
                "total_yards": "1121",
                "plays_offense": "183",
                "yds_per_play_offense": "6.1",
                "turnovers": "5",
                "fumbles_lost": "2",
                "first_down": "64",
                "pass_cmp": "66",
                "pass_att": "98",
                "pass_yds": "684",
                "pass_td": "4",
                "pass_int": "3",
                "pass_net_yds_per_att": "6.8",
                "pass_fd": "31",
                "rush_att": "83",
                "rush_yds": "437",
                "rush_td": "6",
                "rush_yds_per_att": "5.3",
                "rush_fd": "22",
                "penalties": "14",
                "penalties_yds": "97",
                "pen_fd": "11",
                "score_pct": "47.1",
                "turnover_pct": "11.8",
                "exp_pts_def_tot": "-28.60"
            },
            {
                "team": "Baltimore Ravens",
                "g": "3",
                "points": "96",
                "total_yards": "1245",
                "plays_offense": "216",
                "yds_per_play_offense": "5.8",
                "turnovers": "2",
                "fumbles_lost": "1",
                "first_down": "70",
                "pass_cmp": "81",
                "pass_att": "122",
                "pass_yds": "798",
                "pass_td": "5",
                "pass_int": "1",
                "pass_net_yds_per_att": "6.4",
                "pass_fd": "39",
                "rush_att": "91",
                "rush_yds": "447",
                "rush_td": "7",
                "rush_yds_per_att": "4.9",
                "rush_fd": "28",
                "penalties": "19",
                "penalties_yds": "148",
                "pen_fd": "3",
                "score_pct": "48.6",
                "turnover_pct": "5.7",
                "exp_pts_def_tot": "-29.74"
            },
            {
                "team": "Miami Dolphins",
                "g": "3",
                "points": "97",
                "total_yards": "1111",
                "plays_offense": "182",
                "yds_per_play_offense": "6.1",
                "turnovers": "",
                "fumbles_lost": "0",
                "first_down": "68",
                "pass_cmp": "63",
                "pass_att": "80",
                "pass_yds": "676",
                "pass_td": "6",
                "pass_int": "0",
                "pass_net_yds_per_att": "7.9",
                "pass_fd": "35",
                "rush_att": "96",
                "rush_yds": "435",
                "rush_td": "4",
                "rush_yds_per_att": "4.5",
                "rush_fd": "27",
                "penalties": "19",
                "penalties_yds": "155",
                "pen_fd": "6",
                "score_pct": "68.0",
                "turnover_pct": "0.0",
                "exp_pts_def_tot": "-49.57"
            }
        ]

const advancedDefenseStats = [
            {
                "g": "3",
                "pass_att_opp": "77",
                "pass_cmp_opp": "44",
                "pass_yds_opp": "393",
                "pass_td_opp": "3",
                "def_tgt_yds_per_att": "9.2",
                "def_air_yds": "283",
                "def_yac": "163",
                "blitzes": "32",
                "blitz_pct": "34.0%",
                "qb_hurry": "3",
                "qb_hurry_pct": "3.2%",
                "qb_knockdown": "6",
                "qb_knockdown_pct": "7.8%",
                "sacks": "8",
                "pressures": "17",
                "pressures_pct": "18.1%",
                "tackles_missed": "9"
            },
            {
                "g": "3",
                "pass_att_opp": "75",
                "pass_cmp_opp": "46",
                "pass_yds_opp": "394",
                "pass_td_opp": "5",
                "def_tgt_yds_per_att": "7.2",
                "def_air_yds": "194",
                "def_yac": "243",
                "blitzes": "26",
                "blitz_pct": "29.5%",
                "qb_hurry": "18",
                "qb_hurry_pct": "20.5%",
                "qb_knockdown": "5",
                "qb_knockdown_pct": "6.7%",
                "sacks": "6",
                "pressures": "29",
                "pressures_pct": "33.0%",
                "tackles_missed": "15"
            },
            {
                "g": "3",
                "pass_att_opp": "99",
                "pass_cmp_opp": "59",
                "pass_yds_opp": "590",
                "pass_td_opp": "2",
                "def_tgt_yds_per_att": "7.4",
                "def_air_yds": "295",
                "def_yac": "286",
                "blitzes": "20",
                "blitz_pct": "18.7%",
                "qb_hurry": "1",
                "qb_hurry_pct": "0.9%",
                "qb_knockdown": "6",
                "qb_knockdown_pct": "6.1%",
                "sacks": "1",
                "pressures": "8",
                "pressures_pct": "7.5%",
                "tackles_missed": "17"
            },
            {
                "g": "3",
                "pass_att_opp": "93",
                "pass_cmp_opp": "70",
                "pass_yds_opp": "743",
                "pass_td_opp": "8",
                "def_tgt_yds_per_att": "7.2",
                "def_air_yds": "419",
                "def_yac": "350",
                "blitzes": "12",
                "blitz_pct": "12.0%",
                "qb_hurry": "7",
                "qb_hurry_pct": "7.0%",
                "qb_knockdown": "11",
                "qb_knockdown_pct": "11.8%",
                "sacks": "5",
                "pressures": "23",
                "pressures_pct": "23.0%",
                "tackles_missed": "19"
            },
            {
                "g": "3",
                "pass_att_opp": "111",
                "pass_cmp_opp": "71",
                "pass_yds_opp": "722",
                "pass_td_opp": "6",
                "def_tgt_yds_per_att": "6.8",
                "def_air_yds": "328",
                "def_yac": "435",
                "blitzes": "13",
                "blitz_pct": "10.7%",
                "qb_hurry": "6",
                "qb_hurry_pct": "5.0%",
                "qb_knockdown": "7",
                "qb_knockdown_pct": "6.3%",
                "sacks": "6",
                "pressures": "19",
                "pressures_pct": "15.7%",
                "tackles_missed": "31"
            },
            {
                "g": "3",
                "pass_att_opp": "77",
                "pass_cmp_opp": "51",
                "pass_yds_opp": "441",
                "pass_td_opp": "6",
                "def_tgt_yds_per_att": "6.4",
                "def_air_yds": "269",
                "def_yac": "252",
                "blitzes": "26",
                "blitz_pct": "28.3%",
                "qb_hurry": "3",
                "qb_hurry_pct": "3.3%",
                "qb_knockdown": "5",
                "qb_knockdown_pct": "6.5%",
                "sacks": "11",
                "pressures": "19",
                "pressures_pct": "20.7%",
                "tackles_missed": "14"
            },
            {
                "g": "3",
                "pass_att_opp": "99",
                "pass_cmp_opp": "64",
                "pass_yds_opp": "535",
                "pass_td_opp": "5",
                "def_tgt_yds_per_att": "6.1",
                "def_air_yds": "252",
                "def_yac": "300",
                "blitzes": "28",
                "blitz_pct": "24.8%",
                "qb_hurry": "7",
                "qb_hurry_pct": "6.2%",
                "qb_knockdown": "4",
                "qb_knockdown_pct": "4.0%",
                "sacks": "7",
                "pressures": "18",
                "pressures_pct": "15.9%",
                "tackles_missed": "22"
            },
            {
                "g": "4",
                "pass_att_opp": "168",
                "pass_cmp_opp": "107",
                "pass_yds_opp": "1022",
                "pass_td_opp": "5",
                "def_tgt_yds_per_att": "7.3",
                "def_air_yds": "633",
                "def_yac": "430",
                "blitzes": "37",
                "blitz_pct": "20.6%",
                "qb_hurry": "9",
                "qb_hurry_pct": "5.0%",
                "qb_knockdown": "14",
                "qb_knockdown_pct": "8.3%",
                "sacks": "8",
                "pressures": "31",
                "pressures_pct": "17.2%",
                "tackles_missed": "19"
            },
            {
                "g": "3",
                "pass_att_opp": "92",
                "pass_cmp_opp": "68",
                "pass_yds_opp": "864",
                "pass_td_opp": "7",
                "def_tgt_yds_per_att": "9.6",
                "def_air_yds": "546",
                "def_yac": "354",
                "blitzes": "20",
                "blitz_pct": "18.9%",
                "qb_hurry": "15",
                "qb_hurry_pct": "14.2%",
                "qb_knockdown": "9",
                "qb_knockdown_pct": "9.8%",
                "sacks": "4",
                "pressures": "28",
                "pressures_pct": "26.4%",
                "tackles_missed": "20"
            },
            {
                "g": "3",
                "pass_att_opp": "109",
                "pass_cmp_opp": "63",
                "pass_yds_opp": "638",
                "pass_td_opp": "2",
                "def_tgt_yds_per_att": "10.0",
                "def_air_yds": "398",
                "def_yac": "330",
                "blitzes": "45",
                "blitz_pct": "36.0%",
                "qb_hurry": "18",
                "qb_hurry_pct": "14.4%",
                "qb_knockdown": "19",
                "qb_knockdown_pct": "17.4%",
                "sacks": "12",
                "pressures": "49",
                "pressures_pct": "39.2%",
                "tackles_missed": "15"
            },
            {
                "g": "3",
                "pass_att_opp": "83",
                "pass_cmp_opp": "58",
                "pass_yds_opp": "626",
                "pass_td_opp": "7",
                "def_tgt_yds_per_att": "10.5",
                "def_air_yds": "483",
                "def_yac": "227",
                "blitzes": "33",
                "blitz_pct": "32.7%",
                "qb_hurry": "5",
                "qb_hurry_pct": "5.0%",
                "qb_knockdown": "2",
                "qb_knockdown_pct": "2.4%",
                "sacks": "11",
                "pressures": "18",
                "pressures_pct": "17.8%",
                "tackles_missed": "8"
            },
            {
                "g": "3",
                "pass_att_opp": "117",
                "pass_cmp_opp": "76",
                "pass_yds_opp": "504",
                "pass_td_opp": "3",
                "def_tgt_yds_per_att": "6.0",
                "def_air_yds": "271",
                "def_yac": "296",
                "blitzes": "25",
                "blitz_pct": "18.8%",
                "qb_hurry": "8",
                "qb_hurry_pct": "6.0%",
                "qb_knockdown": "17",
                "qb_knockdown_pct": "14.5%",
                "sacks": "10",
                "pressures": "35",
                "pressures_pct": "26.3%",
                "tackles_missed": "16"
            },
            {
                "g": "3",
                "pass_att_opp": "107",
                "pass_cmp_opp": "66",
                "pass_yds_opp": "620",
                "pass_td_opp": "3",
                "def_tgt_yds_per_att": "8.3",
                "def_air_yds": "366",
                "def_yac": "316",
                "blitzes": "29",
                "blitz_pct": "24.2%",
                "qb_hurry": "4",
                "qb_hurry_pct": "3.3%",
                "qb_knockdown": "7",
                "qb_knockdown_pct": "6.5%",
                "sacks": "9",
                "pressures": "20",
                "pressures_pct": "16.7%",
                "tackles_missed": "26"
            },
            {
                "g": "3",
                "pass_att_opp": "118",
                "pass_cmp_opp": "71",
                "pass_yds_opp": "628",
                "pass_td_opp": "5",
                "def_tgt_yds_per_att": "8.1",
                "def_air_yds": "397",
                "def_yac": "271",
                "blitzes": "28",
                "blitz_pct": "21.4%",
                "qb_hurry": "7",
                "qb_hurry_pct": "5.3%",
                "qb_knockdown": "13",
                "qb_knockdown_pct": "11.0%",
                "sacks": "6",
                "pressures": "26",
                "pressures_pct": "19.8%",
                "tackles_missed": "15"
            },
            {
                "g": "3",
                "pass_att_opp": "88",
                "pass_cmp_opp": "58",
                "pass_yds_opp": "549",
                "pass_td_opp": "3",
                "def_tgt_yds_per_att": "9.0",
                "def_air_yds": "295",
                "def_yac": "284",
                "blitzes": "36",
                "blitz_pct": "34.6%",
                "qb_hurry": "4",
                "qb_hurry_pct": "3.8%",
                "qb_knockdown": "8",
                "qb_knockdown_pct": "9.1%",
                "sacks": "7",
                "pressures": "19",
                "pressures_pct": "18.3%",
                "tackles_missed": "14"
            },
            {
                "g": "3",
                "pass_att_opp": "80",
                "pass_cmp_opp": "63",
                "pass_yds_opp": "676",
                "pass_td_opp": "6",
                "def_tgt_yds_per_att": "5.3",
                "def_air_yds": "314",
                "def_yac": "401",
                "blitzes": "39",
                "blitz_pct": "41.1%",
                "qb_hurry": "10",
                "qb_hurry_pct": "10.5%",
                "qb_knockdown": "1",
                "qb_knockdown_pct": "1.3%",
                "sacks": "6",
                "pressures": "17",
                "pressures_pct": "17.9%",
                "tackles_missed": "18"
            },
            {
                "g": "3",
                "pass_att_opp": "83",
                "pass_cmp_opp": "53",
                "pass_yds_opp": "424",
                "pass_td_opp": "2",
                "def_tgt_yds_per_att": "6.4",
                "def_air_yds": "265",
                "def_yac": "220",
                "blitzes": "32",
                "blitz_pct": "32.7%",
                "qb_hurry": "14",
                "qb_hurry_pct": "14.3%",
                "qb_knockdown": "10",
                "qb_knockdown_pct": "12.0%",
                "sacks": "9",
                "pressures": "33",
                "pressures_pct": "33.7%",
                "tackles_missed": "25"
            },
            {
                "g": "3",
                "pass_att_opp": "89",
                "pass_cmp_opp": "63",
                "pass_yds_opp": "630",
                "pass_td_opp": "7",
                "def_tgt_yds_per_att": "6.5",
                "def_air_yds": "361",
                "def_yac": "314",
                "blitzes": "21",
                "blitz_pct": "20.8%",
                "qb_hurry": "5",
                "qb_hurry_pct": "5.0%",
                "qb_knockdown": "5",
                "qb_knockdown_pct": "5.6%",
                "sacks": "8",
                "pressures": "18",
                "pressures_pct": "17.8%",
                "tackles_missed": "18"
            },
            {
                "g": "3",
                "pass_att_opp": "89",
                "pass_cmp_opp": "66",
                "pass_yds_opp": "769",
                "pass_td_opp": "5",
                "def_tgt_yds_per_att": "8.1",
                "def_air_yds": "424",
                "def_yac": "392",
                "blitzes": "25",
                "blitz_pct": "25.0%",
                "qb_hurry": "4",
                "qb_hurry_pct": "4.0%",
                "qb_knockdown": "8",
                "qb_knockdown_pct": "9.0%",
                "sacks": "9",
                "pressures": "21",
                "pressures_pct": "21.0%",
                "tackles_missed": "25"
            },
            {
                "g": "3",
                "pass_att_opp": "119",
                "pass_cmp_opp": "79",
                "pass_yds_opp": "756",
                "pass_td_opp": "4",
                "def_tgt_yds_per_att": "8.1",
                "def_air_yds": "462",
                "def_yac": "356",
                "blitzes": "36",
                "blitz_pct": "26.5%",
                "qb_hurry": "4",
                "qb_hurry_pct": "2.9%",
                "qb_knockdown": "10",
                "qb_knockdown_pct": "8.4%",
                "sacks": "8",
                "pressures": "22",
                "pressures_pct": "16.2%",
                "tackles_missed": "14"
            },
            {
                "g": "3",
                "pass_att_opp": "86",
                "pass_cmp_opp": "56",
                "pass_yds_opp": "622",
                "pass_td_opp": "5",
                "def_tgt_yds_per_att": "6.4",
                "def_air_yds": "240",
                "def_yac": "417",
                "blitzes": "27",
                "blitz_pct": "27.3%",
                "qb_hurry": "2",
                "qb_hurry_pct": "2.0%",
                "qb_knockdown": "5",
                "qb_knockdown_pct": "5.8%",
                "sacks": "6",
                "pressures": "13",
                "pressures_pct": "13.1%",
                "tackles_missed": "39"
            },
            {
                "g": "3",
                "pass_att_opp": "98",
                "pass_cmp_opp": "66",
                "pass_yds_opp": "684",
                "pass_td_opp": "4",
                "def_tgt_yds_per_att": "6.9",
                "def_air_yds": "356",
                "def_yac": "346",
                "blitzes": "22",
                "blitz_pct": "21.4%",
                "qb_hurry": "7",
                "qb_hurry_pct": "6.8%",
                "qb_knockdown": "10",
                "qb_knockdown_pct": "10.2%",
                "sacks": "2",
                "pressures": "19",
                "pressures_pct": "18.4%",
                "tackles_missed": "30"
            },
            {
                "g": "3",
                "pass_att_opp": "97",
                "pass_cmp_opp": "56",
                "pass_yds_opp": "557",
                "pass_td_opp": "3",
                "def_tgt_yds_per_att": "9.6",
                "def_air_yds": "371",
                "def_yac": "200",
                "blitzes": "28",
                "blitz_pct": "25.9%",
                "qb_hurry": "4",
                "qb_hurry_pct": "3.7%",
                "qb_knockdown": "14",
                "qb_knockdown_pct": "14.4%",
                "sacks": "3",
                "pressures": "21",
                "pressures_pct": "19.4%",
                "tackles_missed": "16"
            },
            {
                "g": "3",
                "pass_att_opp": "92",
                "pass_cmp_opp": "66",
                "pass_yds_opp": "740",
                "pass_td_opp": "5",
                "def_tgt_yds_per_att": "7.0",
                "def_air_yds": "466",
                "def_yac": "315",
                "blitzes": "40",
                "blitz_pct": "37.0%",
                "qb_hurry": "9",
                "qb_hurry_pct": "8.3%",
                "qb_knockdown": "13",
                "qb_knockdown_pct": "14.1%",
                "sacks": "8",
                "pressures": "30",
                "pressures_pct": "27.8%",
                "tackles_missed": "34"
            },
            {
                "g": "3",
                "pass_att_opp": "94",
                "pass_cmp_opp": "64",
                "pass_yds_opp": "711",
                "pass_td_opp": "4",
                "def_tgt_yds_per_att": "8.5",
                "def_air_yds": "424",
                "def_yac": "278",
                "blitzes": "28",
                "blitz_pct": "25.9%",
                "qb_hurry": "3",
                "qb_hurry_pct": "2.8%",
                "qb_knockdown": "9",
                "qb_knockdown_pct": "9.6%",
                "sacks": "7",
                "pressures": "19",
                "pressures_pct": "17.6%",
                "tackles_missed": "23"
            },
            {
                "g": "3",
                "pass_att_opp": "92",
                "pass_cmp_opp": "59",
                "pass_yds_opp": "496",
                "pass_td_opp": "4",
                "def_tgt_yds_per_att": "7.0",
                "def_air_yds": "373",
                "def_yac": "216",
                "blitzes": "24",
                "blitz_pct": "21.4%",
                "qb_hurry": "4",
                "qb_hurry_pct": "3.6%",
                "qb_knockdown": "8",
                "qb_knockdown_pct": "8.7%",
                "sacks": "12",
                "pressures": "24",
                "pressures_pct": "21.4%",
                "tackles_missed": "3"
            },
            {
                "g": "3",
                "pass_att_opp": "122",
                "pass_cmp_opp": "81",
                "pass_yds_opp": "798",
                "pass_td_opp": "5",
                "def_tgt_yds_per_att": "8.0",
                "def_air_yds": "509",
                "def_yac": "287",
                "blitzes": "27",
                "blitz_pct": "20.5%",
                "qb_hurry": "8",
                "qb_hurry_pct": "6.1%",
                "qb_knockdown": "14",
                "qb_knockdown_pct": "11.5%",
                "sacks": "3",
                "pressures": "25",
                "pressures_pct": "18.9%",
                "tackles_missed": "23"
            },
            {
                "g": "3",
                "pass_att_opp": "107",
                "pass_cmp_opp": "62",
                "pass_yds_opp": "546",
                "pass_td_opp": "2",
                "def_tgt_yds_per_att": "7.7",
                "def_air_yds": "246",
                "def_yac": "345",
                "blitzes": "18",
                "blitz_pct": "14.2%",
                "qb_hurry": "9",
                "qb_hurry_pct": "7.1%",
                "qb_knockdown": "11",
                "qb_knockdown_pct": "10.3%",
                "sacks": "7",
                "pressures": "27",
                "pressures_pct": "21.3%",
                "tackles_missed": "24"
            },
            {
                "g": "4",
                "pass_att_opp": "152",
                "pass_cmp_opp": "101",
                "pass_yds_opp": "829",
                "pass_td_opp": "6",
                "def_tgt_yds_per_att": "7.0",
                "def_air_yds": "415",
                "def_yac": "495",
                "blitzes": "26",
                "blitz_pct": "14.9%",
                "qb_hurry": "16",
                "qb_hurry_pct": "9.2%",
                "qb_knockdown": "15",
                "qb_knockdown_pct": "9.9%",
                "sacks": "12",
                "pressures": "43",
                "pressures_pct": "24.7%",
                "tackles_missed": "28"
            },
            {
                "g": "3",
                "pass_att_opp": "92",
                "pass_cmp_opp": "63",
                "pass_yds_opp": "486",
                "pass_td_opp": "4",
                "def_tgt_yds_per_att": "7.2",
                "def_air_yds": "287",
                "def_yac": "229",
                "blitzes": "18",
                "blitz_pct": "17.0%",
                "qb_hurry": "4",
                "qb_hurry_pct": "3.8%",
                "qb_knockdown": "7",
                "qb_knockdown_pct": "7.6%",
                "sacks": "5",
                "pressures": "16",
                "pressures_pct": "15.1%",
                "tackles_missed": "22"
            },
            {
                "g": "3",
                "pass_att_opp": "102",
                "pass_cmp_opp": "66",
                "pass_yds_opp": "639",
                "pass_td_opp": "4",
                "def_tgt_yds_per_att": "6.3",
                "def_air_yds": "283",
                "def_yac": "419",
                "blitzes": "43",
                "blitz_pct": "34.7%",
                "qb_hurry": "3",
                "qb_hurry_pct": "2.4%",
                "qb_knockdown": "11",
                "qb_knockdown_pct": "10.8%",
                "sacks": "8",
                "pressures": "22",
                "pressures_pct": "17.7%",
                "tackles_missed": "14"
            },
            {
                "g": "3",
                "pass_att_opp": "97",
                "pass_cmp_opp": "55",
                "pass_yds_opp": "687",
                "pass_td_opp": "5",
                "def_tgt_yds_per_att": "10.1",
                "def_air_yds": "450",
                "def_yac": "283",
                "blitzes": "32",
                "blitz_pct": "28.3%",
                "qb_hurry": "5",
                "qb_hurry_pct": "4.4%",
                "qb_knockdown": "10",
                "qb_knockdown_pct": "10.3%",
                "sacks": "9",
                "pressures": "24",
                "pressures_pct": "21.2%",
                "tackles_missed": "22"
            }
        ]
=======
    {
        "team": "Los Angeles Rams",
        "g": "2",
        "points": "28",
        "total_yards": "517",
        "plays_offense": "121",
        "yds_per_play_offense": "4.3",
        "turnovers": "3",
        "fumbles_lost": "2",
        "first_down": "36",
        "pass_cmp": "38",
        "pass_att": "60",
        "pass_yds": "294",
        "pass_td": "1",
        "pass_int": "1",
        "pass_net_yds_per_att": "4.3",
        "pass_fd": "17",
        "rush_att": "53",
        "rush_yds": "223",
        "rush_td": "0",
        "rush_yds_per_att": "4.2",
        "rush_fd": "15",
        "penalties": "21",
        "penalties_yds": "142",
        "pen_fd": "4",
        "score_pct": "40.0",
        "turnover_pct": "15.0",
        "exp_pts_def_tot": "10.29"
    },
    {
        "team": "Pittsburgh Steelers",
        "g": "9",
        "points": "146",
        "total_yards": "2724",
        "plays_offense": "531",
        "yds_per_play_offense": "5.1",
        "turnovers": "16",
        "fumbles_lost": "6",
        "first_down": "154",
        "pass_cmp": "190",
        "pass_att": "304",
        "pass_yds": "1940",
        "pass_td": "8",
        "pass_int": "10",
        "pass_net_yds_per_att": "6.0",
        "pass_fd": "91",
        "rush_att": "205",
        "rush_yds": "784",
        "rush_td": "7",
        "rush_yds_per_att": "3.8",
        "rush_fd": "53",
        "penalties": "61",
        "penalties_yds": "550",
        "pen_fd": "10",
        "score_pct": "29.9",
        "turnover_pct": "15.5",
        "exp_pts_def_tot": "20.44"
    },
    {
        "team": "Minnesota Vikings",
        "g": "9",
        "points": "157",
        "total_yards": "2798",
        "plays_offense": "557",
        "yds_per_play_offense": "5.0",
        "turnovers": "20",
        "fumbles_lost": "5",
        "first_down": "164",
        "pass_cmp": "216",
        "pass_att": "338",
        "pass_yds": "2087",
        "pass_td": "14",
        "pass_int": "15",
        "pass_net_yds_per_att": "5.7",
        "pass_fd": "118",
        "rush_att": "189",
        "rush_yds": "711",
        "rush_td": "4",
        "rush_yds_per_att": "3.8",
        "rush_fd": "30",
        "penalties": "64",
        "penalties_yds": "521",
        "pen_fd": "16",
        "score_pct": "25.0",
        "turnover_pct": "20.0",
        "exp_pts_def_tot": "54.36"
    },
    {
        "team": "Philadelphia Eagles",
        "g": "9",
        "points": "161",
        "total_yards": "2467",
        "plays_offense": "518",
        "yds_per_play_offense": "4.8",
        "turnovers": "12",
        "fumbles_lost": "6",
        "first_down": "149",
        "pass_cmp": "173",
        "pass_att": "285",
        "pass_yds": "1561",
        "pass_td": "8",
        "pass_int": "6",
        "pass_net_yds_per_att": "5.0",
        "pass_fd": "86",
        "rush_att": "208",
        "rush_yds": "906",
        "rush_td": "6",
        "rush_yds_per_att": "4.4",
        "rush_fd": "52",
        "penalties": "41",
        "penalties_yds": "306",
        "pen_fd": "11",
        "score_pct": "32.6",
        "turnover_pct": "11.6",
        "exp_pts_def_tot": "25.40"
    },
    {
        "team": "Kansas City Chiefs",
        "g": "9",
        "points": "161",
        "total_yards": "2609",
        "plays_offense": "514",
        "yds_per_play_offense": "5.1",
        "turnovers": "8",
        "fumbles_lost": "3",
        "first_down": "155",
        "pass_cmp": "191",
        "pass_att": "290",
        "pass_yds": "1860",
        "pass_td": "13",
        "pass_int": "5",
        "pass_net_yds_per_att": "6.0",
        "pass_fd": "94",
        "rush_att": "205",
        "rush_yds": "749",
        "rush_td": "5",
        "rush_yds_per_att": "3.7",
        "rush_fd": "46",
        "penalties": "58",
        "penalties_yds": "465",
        "pen_fd": "15",
        "score_pct": "35.6",
        "turnover_pct": "9.2",
        "exp_pts_def_tot": "-1.22"
    },
    {
        "team": "Chicago Bears",
        "g": "9",
        "points": "167",
        "total_yards": "2911",
        "plays_offense": "542",
        "yds_per_play_offense": "5.4",
        "turnovers": "16",
        "fumbles_lost": "8",
        "first_down": "155",
        "pass_cmp": "167",
        "pass_att": "271",
        "pass_yds": "1714",
        "pass_td": "6",
        "pass_int": "8",
        "pass_net_yds_per_att": "5.8",
        "pass_fd": "86",
        "rush_att": "247",
        "rush_yds": "1197",
        "rush_td": "9",
        "rush_yds_per_att": "4.8",
        "rush_fd": "60",
        "penalties": "61",
        "penalties_yds": "433",
        "pen_fd": "9",
        "score_pct": "34.3",
        "turnover_pct": "15.2",
        "exp_pts_def_tot": "32.57"
    },
    {
        "team": "Detroit Lions",
        "g": "9",
        "points": "171",
        "total_yards": "3105",
        "plays_offense": "567",
        "yds_per_play_offense": "5.5",
        "turnovers": "18",
        "fumbles_lost": "5",
        "first_down": "186",
        "pass_cmp": "216",
        "pass_att": "339",
        "pass_yds": "2198",
        "pass_td": "7",
        "pass_int": "13",
        "pass_net_yds_per_att": "6.1",
        "pass_fd": "110",
        "rush_att": "204",
        "rush_yds": "907",
        "rush_td": "9",
        "rush_yds_per_att": "4.4",
        "rush_fd": "48",
        "penalties": "56",
        "penalties_yds": "431",
        "pen_fd": "28",
        "score_pct": "32.7",
        "turnover_pct": "17.8",
        "exp_pts_def_tot": "14.37"
    },
    {
        "team": "Denver Broncos",
        "g": "10",
        "points": "177",
        "total_yards": "2957",
        "plays_offense": "629",
        "yds_per_play_offense": "4.7",
        "turnovers": "12",
        "fumbles_lost": "5",
        "first_down": "185",
        "pass_cmp": "219",
        "pass_att": "329",
        "pass_yds": "1922",
        "pass_td": "12",
        "pass_int": "7",
        "pass_net_yds_per_att": "5.3",
        "pass_fd": "105",
        "rush_att": "265",
        "rush_yds": "1035",
        "rush_td": "6",
        "rush_yds_per_att": "3.9",
        "rush_fd": "53",
        "penalties": "70",
        "penalties_yds": "474",
        "pen_fd": "27",
        "score_pct": "31.5",
        "turnover_pct": "9.9",
        "exp_pts_def_tot": "40.27"
    },
    {
        "team": "Buffalo Bills",
        "g": "10",
        "points": "193",
        "total_yards": "3361",
        "plays_offense": "618",
        "yds_per_play_offense": "5.4",
        "turnovers": "19",
        "fumbles_lost": "8",
        "first_down": "197",
        "pass_cmp": "234",
        "pass_att": "340",
        "pass_yds": "2129",
        "pass_td": "13",
        "pass_int": "11",
        "pass_net_yds_per_att": "5.8",
        "pass_fd": "120",
        "rush_att": "253",
        "rush_yds": "1232",
        "rush_td": "6",
        "rush_yds_per_att": "4.9",
        "rush_fd": "61",
        "penalties": "77",
        "penalties_yds": "596",
        "pen_fd": "16",
        "score_pct": "34.0",
        "turnover_pct": "17.5",
        "exp_pts_def_tot": "2.65"
    },
    {
        "team": "Green Bay Packers",
        "g": "9",
        "points": "194",
        "total_yards": "2880",
        "plays_offense": "544",
        "yds_per_play_offense": "5.3",
        "turnovers": "19",
        "fumbles_lost": "9",
        "first_down": "175",
        "pass_cmp": "183",
        "pass_att": "282",
        "pass_yds": "1863",
        "pass_td": "13",
        "pass_int": "10",
        "pass_net_yds_per_att": "6.1",
        "pass_fd": "96",
        "rush_att": "240",
        "rush_yds": "1017",
        "rush_td": "8",
        "rush_yds_per_att": "4.2",
        "rush_fd": "66",
        "penalties": "55",
        "penalties_yds": "442",
        "pen_fd": "13",
        "score_pct": "33.7",
        "turnover_pct": "18.4",
        "exp_pts_def_tot": "1.89"
    },
    {
        "team": "San Francisco 49ers",
        "g": "9",
        "points": "202",
        "total_yards": "2733",
        "plays_offense": "535",
        "yds_per_play_offense": "5.1",
        "turnovers": "15",
        "fumbles_lost": "5",
        "first_down": "161",
        "pass_cmp": "179",
        "pass_att": "289",
        "pass_yds": "1777",
        "pass_td": "11",
        "pass_int": "10",
        "pass_net_yds_per_att": "5.7",
        "pass_fd": "96",
        "rush_att": "224",
        "rush_yds": "956",
        "rush_td": "11",
        "rush_yds_per_att": "4.3",
        "rush_fd": "53",
        "penalties": "46",
        "penalties_yds": "352",
        "pen_fd": "12",
        "score_pct": "37.9",
        "turnover_pct": "14.7",
        "exp_pts_def_tot": "-6.95"
    },
    {
        "team": "Miami Dolphins",
        "g": "9",
        "points": "202",
        "total_yards": "2752",
        "plays_offense": "522",
        "yds_per_play_offense": "5.3",
        "turnovers": "8",
        "fumbles_lost": "3",
        "first_down": "164",
        "pass_cmp": "174",
        "pass_att": "274",
        "pass_yds": "1722",
        "pass_td": "8",
        "pass_int": "5",
        "pass_net_yds_per_att": "6.0",
        "pass_fd": "91",
        "rush_att": "234",
        "rush_yds": "1030",
        "rush_td": "10",
        "rush_yds_per_att": "4.4",
        "rush_fd": "59",
        "penalties": "58",
        "penalties_yds": "500",
        "pen_fd": "14",
        "score_pct": "40.8",
        "turnover_pct": "8.2",
        "exp_pts_def_tot": "-4.06"
    },
    {
        "team": "Cleveland Browns",
        "g": "9",
        "points": "213",
        "total_yards": "2954",
        "plays_offense": "537",
        "yds_per_play_offense": "5.5",
        "turnovers": "5",
        "fumbles_lost": "4",
        "first_down": "156",
        "pass_cmp": "158",
        "pass_att": "264",
        "pass_yds": "1851",
        "pass_td": "12",
        "pass_int": "1",
        "pass_net_yds_per_att": "6.4",
        "pass_fd": "88",
        "rush_att": "246",
        "rush_yds": "1103",
        "rush_td": "11",
        "rush_yds_per_att": "4.5",
        "rush_fd": "58",
        "penalties": "57",
        "penalties_yds": "450",
        "pen_fd": "10",
        "score_pct": "32.7",
        "turnover_pct": "3.7",
        "exp_pts_def_tot": "-22.92"
    },
    {
        "team": "New York Jets",
        "g": "10",
        "points": "214",
        "total_yards": "3023",
        "plays_offense": "621",
        "yds_per_play_offense": "4.9",
        "turnovers": "7",
        "fumbles_lost": "5",
        "first_down": "197",
        "pass_cmp": "167",
        "pass_att": "279",
        "pass_yds": "1683",
        "pass_td": "7",
        "pass_int": "2",
        "pass_net_yds_per_att": "5.4",
        "pass_fd": "86",
        "rush_att": "310",
        "rush_yds": "1340",
        "rush_td": "14",
        "rush_yds_per_att": "4.3",
        "rush_fd": "83",
        "penalties": "62",
        "penalties_yds": "607",
        "pen_fd": "28",
        "score_pct": "39.8",
        "turnover_pct": "6.8",
        "exp_pts_def_tot": "-41.92"
    },
    {
        "team": "Washington Commanders",
        "g": "10",
        "points": "217",
        "total_yards": "3249",
        "plays_offense": "591",
        "yds_per_play_offense": "5.5",
        "turnovers": "10",
        "fumbles_lost": "6",
        "first_down": "198",
        "pass_cmp": "178",
        "pass_att": "270",
        "pass_yds": "1822",
        "pass_td": "17",
        "pass_int": "4",
        "pass_net_yds_per_att": "6.1",
        "pass_fd": "102",
        "rush_att": "294",
        "rush_yds": "1427",
        "rush_td": "10",
        "rush_yds_per_att": "4.9",
        "rush_fd": "79",
        "penalties": "56",
        "penalties_yds": "468",
        "pen_fd": "17",
        "score_pct": "39.6",
        "turnover_pct": "10.4",
        "exp_pts_def_tot": "-56.84"
    },
    {
        "team": "Los Angeles Rams",
        "g": "9",
        "points": "217",
        "total_yards": "3124",
        "plays_offense": "552",
        "yds_per_play_offense": "5.7",
        "turnovers": "13",
        "fumbles_lost": "4",
        "first_down": "178",
        "pass_cmp": "169",
        "pass_att": "259",
        "pass_yds": "1976",
        "pass_td": "16",
        "pass_int": "9",
        "pass_net_yds_per_att": "7.0",
        "pass_fd": "95",
        "rush_att": "269",
        "rush_yds": "1148",
        "rush_td": "7",
        "rush_yds_per_att": "4.3",
        "rush_fd": "67",
        "penalties": "67",
        "penalties_yds": "582",
        "pen_fd": "16",
        "score_pct": "42.7",
        "turnover_pct": "12.5",
        "exp_pts_def_tot": "-35.21"
    },
    {
        "team": "New England Patriots",
        "g": "10",
        "points": "220",
        "total_yards": "3395",
        "plays_offense": "629",
        "yds_per_play_offense": "5.4",
        "turnovers": "8",
        "fumbles_lost": "4",
        "first_down": "201",
        "pass_cmp": "202",
        "pass_att": "309",
        "pass_yds": "2090",
        "pass_td": "12",
        "pass_int": "4",
        "pass_net_yds_per_att": "6.3",
        "pass_fd": "109",
        "rush_att": "295",
        "rush_yds": "1305",
        "rush_td": "10",
        "rush_yds_per_att": "4.4",
        "rush_fd": "72",
        "penalties": "59",
        "penalties_yds": "472",
        "pen_fd": "20",
        "score_pct": "38.8",
        "turnover_pct": "5.8",
        "exp_pts_def_tot": "-57.72"
    },
    {
        "team": "Arizona Cardinals",
        "g": "10",
        "points": "220",
        "total_yards": "3460",
        "plays_offense": "631",
        "yds_per_play_offense": "5.5",
        "turnovers": "11",
        "fumbles_lost": "6",
        "first_down": "213",
        "pass_cmp": "221",
        "pass_att": "323",
        "pass_yds": "2185",
        "pass_td": "11",
        "pass_int": "5",
        "pass_net_yds_per_att": "6.3",
        "pass_fd": "122",
        "rush_att": "284",
        "rush_yds": "1275",
        "rush_td": "10",
        "rush_yds_per_att": "4.5",
        "rush_fd": "77",
        "penalties": "50",
        "penalties_yds": "394",
        "pen_fd": "14",
        "score_pct": "46.2",
        "turnover_pct": "10.8",
        "exp_pts_def_tot": "-70.14"
    },
    {
        "team": "Seattle Seahawks",
        "g": "9",
        "points": "221",
        "total_yards": "3218",
        "plays_offense": "581",
        "yds_per_play_offense": "5.5",
        "turnovers": "9",
        "fumbles_lost": "3",
        "first_down": "184",
        "pass_cmp": "195",
        "pass_att": "296",
        "pass_yds": "1963",
        "pass_td": "14",
        "pass_int": "6",
        "pass_net_yds_per_att": "6.2",
        "pass_fd": "97",
        "rush_att": "264",
        "rush_yds": "1255",
        "rush_td": "9",
        "rush_yds_per_att": "4.8",
        "rush_fd": "68",
        "penalties": "71",
        "penalties_yds": "582",
        "pen_fd": "19",
        "score_pct": "35.5",
        "turnover_pct": "8.4",
        "exp_pts_def_tot": "-21.63"
    },
    {
        "team": "New York Giants",
        "g": "10",
        "points": "222",
        "total_yards": "3313",
        "plays_offense": "590",
        "yds_per_play_offense": "5.6",
        "turnovers": "8",
        "fumbles_lost": "7",
        "first_down": "175",
        "pass_cmp": "192",
        "pass_att": "275",
        "pass_yds": "1842",
        "pass_td": "12",
        "pass_int": "1",
        "pass_net_yds_per_att": "5.9",
        "pass_fd": "91",
        "rush_att": "279",
        "rush_yds": "1471",
        "rush_td": "8",
        "rush_yds_per_att": "5.3",
        "rush_fd": "72",
        "penalties": "71",
        "penalties_yds": "590",
        "pen_fd": "12",
        "score_pct": "37.4",
        "turnover_pct": "7.5",
        "exp_pts_def_tot": "-29.40"
    },
    {
        "team": "Indianapolis Colts",
        "g": "10",
        "points": "223",
        "total_yards": "3867",
        "plays_offense": "684",
        "yds_per_play_offense": "5.7",
        "turnovers": "17",
        "fumbles_lost": "9",
        "first_down": "219",
        "pass_cmp": "226",
        "pass_att": "328",
        "pass_yds": "2384",
        "pass_td": "14",
        "pass_int": "8",
        "pass_net_yds_per_att": "6.8",
        "pass_fd": "119",
        "rush_att": "334",
        "rush_yds": "1483",
        "rush_td": "9",
        "rush_yds_per_att": "4.4",
        "rush_fd": "84",
        "penalties": "57",
        "penalties_yds": "471",
        "pen_fd": "16",
        "score_pct": "37.5",
        "turnover_pct": "15.2",
        "exp_pts_def_tot": "-33.17"
    },
    {
        "team": "Houston Texans",
        "g": "10",
        "points": "226",
        "total_yards": "2880",
        "plays_offense": "585",
        "yds_per_play_offense": "4.9",
        "turnovers": "18",
        "fumbles_lost": "5",
        "first_down": "169",
        "pass_cmp": "167",
        "pass_att": "307",
        "pass_yds": "1747",
        "pass_td": "21",
        "pass_int": "13",
        "pass_net_yds_per_att": "5.2",
        "pass_fd": "92",
        "rush_att": "249",
        "rush_yds": "1133",
        "rush_td": "6",
        "rush_yds_per_att": "4.6",
        "rush_fd": "59",
        "penalties": "67",
        "penalties_yds": "485",
        "pen_fd": "18",
        "score_pct": "33.9",
        "turnover_pct": "14.4",
        "exp_pts_def_tot": "6.51"
    },
    {
        "team": "Atlanta Falcons",
        "g": "10",
        "points": "236",
        "total_yards": "3528",
        "plays_offense": "643",
        "yds_per_play_offense": "5.5",
        "turnovers": "10",
        "fumbles_lost": "3",
        "first_down": "208",
        "pass_cmp": "242",
        "pass_att": "344",
        "pass_yds": "2234",
        "pass_td": "17",
        "pass_int": "7",
        "pass_net_yds_per_att": "6.3",
        "pass_fd": "115",
        "rush_att": "290",
        "rush_yds": "1294",
        "rush_td": "5",
        "rush_yds_per_att": "4.5",
        "rush_fd": "83",
        "penalties": "73",
        "penalties_yds": "573",
        "pen_fd": "10",
        "score_pct": "46.0",
        "turnover_pct": "9.0",
        "exp_pts_def_tot": "-43.46"
    },
    {
        "team": "Tennessee Titans",
        "g": "9",
        "points": "240",
        "total_yards": "2462",
        "plays_offense": "511",
        "yds_per_play_offense": "4.8",
        "turnovers": "6",
        "fumbles_lost": "3",
        "first_down": "154",
        "pass_cmp": "160",
        "pass_att": "249",
        "pass_yds": "1410",
        "pass_td": "13",
        "pass_int": "3",
        "pass_net_yds_per_att": "5.3",
        "pass_fd": "76",
        "rush_att": "244",
        "rush_yds": "1052",
        "rush_td": "10",
        "rush_yds_per_att": "4.3",
        "rush_fd": "57",
        "penalties": "60",
        "penalties_yds": "495",
        "pen_fd": "21",
        "score_pct": "40.8",
        "turnover_pct": "5.1",
        "exp_pts_def_tot": "-18.91"
    },
    {
        "team": "New Orleans Saints",
        "g": "10",
        "points": "246",
        "total_yards": "3856",
        "plays_offense": "639",
        "yds_per_play_offense": "6.0",
        "turnovers": "15",
        "fumbles_lost": "3",
        "first_down": "205",
        "pass_cmp": "218",
        "pass_att": "343",
        "pass_yds": "2446",
        "pass_td": "8",
        "pass_int": "12",
        "pass_net_yds_per_att": "6.7",
        "pass_fd": "110",
        "rush_att": "274",
        "rush_yds": "1410",
        "rush_td": "14",
        "rush_yds_per_att": "5.1",
        "rush_fd": "76",
        "penalties": "67",
        "penalties_yds": "549",
        "pen_fd": "19",
        "score_pct": "39.3",
        "turnover_pct": "13.4",
        "exp_pts_def_tot": "-46.22"
    },
    {
        "team": "Las Vegas Raiders",
        "g": "9",
        "points": "251",
        "total_yards": "2925",
        "plays_offense": "555",
        "yds_per_play_offense": "5.3",
        "turnovers": "5",
        "fumbles_lost": "0",
        "first_down": "172",
        "pass_cmp": "189",
        "pass_att": "280",
        "pass_yds": "1756",
        "pass_td": "15",
        "pass_int": "5",
        "pass_net_yds_per_att": "5.9",
        "pass_fd": "100",
        "rush_att": "258",
        "rush_yds": "1169",
        "rush_td": "10",
        "rush_yds_per_att": "4.5",
        "rush_fd": "57",
        "penalties": "64",
        "penalties_yds": "485",
        "pen_fd": "15",
        "score_pct": "42.6",
        "turnover_pct": "5.0",
        "exp_pts_def_tot": "-30.19"
    },
    {
        "team": "Baltimore Ravens",
        "g": "10",
        "points": "253",
        "total_yards": "3679",
        "plays_offense": "645",
        "yds_per_play_offense": "5.7",
        "turnovers": "10",
        "fumbles_lost": "4",
        "first_down": "215",
        "pass_cmp": "261",
        "pass_att": "398",
        "pass_yds": "2949",
        "pass_td": "22",
        "pass_int": "6",
        "pass_net_yds_per_att": "6.9",
        "pass_fd": "154",
        "rush_att": "216",
        "rush_yds": "730",
        "rush_td": "7",
        "rush_yds_per_att": "3.4",
        "rush_fd": "36",
        "penalties": "56",
        "penalties_yds": "455",
        "pen_fd": "25",
        "score_pct": "42.2",
        "turnover_pct": "9.2",
        "exp_pts_def_tot": "-75.21"
    },
    {
        "team": "Dallas Cowboys",
        "g": "9",
        "points": "259",
        "total_yards": "3266",
        "plays_offense": "559",
        "yds_per_play_offense": "5.8",
        "turnovers": "8",
        "fumbles_lost": "3",
        "first_down": "183",
        "pass_cmp": "163",
        "pass_att": "243",
        "pass_yds": "1897",
        "pass_td": "15",
        "pass_int": "5",
        "pass_net_yds_per_att": "7.1",
        "pass_fd": "87",
        "rush_att": "293",
        "rush_yds": "1369",
        "rush_td": "15",
        "rush_yds_per_att": "4.7",
        "rush_fd": "84",
        "penalties": "69",
        "penalties_yds": "505",
        "pen_fd": "12",
        "score_pct": "46.5",
        "turnover_pct": "7.9",
        "exp_pts_def_tot": "-77.25"
    },
    {
        "team": "Cincinnati Bengals",
        "g": "10",
        "points": "262",
        "total_yards": "3475",
        "plays_offense": "654",
        "yds_per_play_offense": "5.3",
        "turnovers": "10",
        "fumbles_lost": "4",
        "first_down": "214",
        "pass_cmp": "220",
        "pass_att": "334",
        "pass_yds": "2202",
        "pass_td": "17",
        "pass_int": "6",
        "pass_net_yds_per_att": "6.3",
        "pass_fd": "112",
        "rush_att": "303",
        "rush_yds": "1273",
        "rush_td": "13",
        "rush_yds_per_att": "4.2",
        "rush_fd": "87",
        "penalties": "56",
        "penalties_yds": "431",
        "pen_fd": "15",
        "score_pct": "40.2",
        "turnover_pct": "9.3",
        "exp_pts_def_tot": "-75.54"
    },
    {
        "team": "Jacksonville Jaguars",
        "g": "10",
        "points": "264",
        "total_yards": "3906",
        "plays_offense": "664",
        "yds_per_play_offense": "5.9",
        "turnovers": "8",
        "fumbles_lost": "3",
        "first_down": "224",
        "pass_cmp": "239",
        "pass_att": "342",
        "pass_yds": "2612",
        "pass_td": "19",
        "pass_int": "5",
        "pass_net_yds_per_att": "7.2",
        "pass_fd": "134",
        "rush_att": "301",
        "rush_yds": "1294",
        "rush_td": "11",
        "rush_yds_per_att": "4.3",
        "rush_fd": "69",
        "penalties": "71",
        "penalties_yds": "549",
        "pen_fd": "21",
        "score_pct": "45.4",
        "turnover_pct": "6.5",
        "exp_pts_def_tot": "-87.69"
    },
    {
        "team": "Tampa Bay Buccaneers",
        "g": "10",
        "points": "266",
        "total_yards": "3893",
        "plays_offense": "664",
        "yds_per_play_offense": "5.9",
        "turnovers": "12",
        "fumbles_lost": "7",
        "first_down": "223",
        "pass_cmp": "258",
        "pass_att": "376",
        "pass_yds": "2641",
        "pass_td": "20",
        "pass_int": "5",
        "pass_net_yds_per_att": "6.5",
        "pass_fd": "133",
        "rush_att": "260",
        "rush_yds": "1252",
        "rush_td": "9",
        "rush_yds_per_att": "4.8",
        "rush_fd": "70",
        "penalties": "58",
        "penalties_yds": "565",
        "pen_fd": "20",
        "score_pct": "45.3",
        "turnover_pct": "9.4",
        "exp_pts_def_tot": "-95.94"
    },
    {
        "team": "Carolina Panthers",
        "g": "10",
        "points": "310",
        "total_yards": "3869",
        "plays_offense": "668",
        "yds_per_play_offense": "5.8",
        "turnovers": "11",
        "fumbles_lost": "6",
        "first_down": "234",
        "pass_cmp": "211",
        "pass_att": "307",
        "pass_yds": "2268",
        "pass_td": "18",
        "pass_int": "5",
        "pass_net_yds_per_att": "7.1",
        "pass_fd": "119",
        "rush_att": "349",
        "rush_yds": "1601",
        "rush_td": "17",
        "rush_yds_per_att": "4.6",
        "rush_fd": "94",
        "penalties": "59",
        "penalties_yds": "516",
        "pen_fd": "21",
        "score_pct": "48.7",
        "turnover_pct": "8.8",
        "exp_pts_def_tot": "-101.88"
    }
]

const advancedDefenseStats = [
    {
        "g": "10",
        "pass_att_opp": "344",
        "pass_cmp_opp": "242",
        "pass_yds_opp": "2234",
        "pass_td_opp": "17",
        "def_tgt_yds_per_att": "6.7",
        "def_air_yds": "1184",
        "def_yac": "1101",
        "blitzes": "89",
        "blitz_pct": "23.4%",
        "qb_hurry": "29",
        "qb_hurry_pct": "7.6%",
        "qb_knockdown": "28",
        "qb_knockdown_pct": "8.1%",
        "sacks": "9",
        "pressures": "66",
        "pressures_pct": "17.4%",
        "tackles_missed": "58"
    },
    {
        "g": "10",
        "pass_att_opp": "340",
        "pass_cmp_opp": "234",
        "pass_yds_opp": "2129",
        "pass_td_opp": "13",
        "def_tgt_yds_per_att": "6.5",
        "def_air_yds": "1131",
        "def_yac": "1166",
        "blitzes": "65",
        "blitz_pct": "17.2%",
        "qb_hurry": "20",
        "qb_hurry_pct": "5.3%",
        "qb_knockdown": "32",
        "qb_knockdown_pct": "9.4%",
        "sacks": "25",
        "pressures": "77",
        "pressures_pct": "20.3%",
        "tackles_missed": "39"
    },
    {
        "g": "10",
        "pass_att_opp": "307",
        "pass_cmp_opp": "211",
        "pass_yds_opp": "2268",
        "pass_td_opp": "18",
        "def_tgt_yds_per_att": "8.0",
        "def_air_yds": "1232",
        "def_yac": "1035",
        "blitzes": "92",
        "blitz_pct": "27.6%",
        "qb_hurry": "16",
        "qb_hurry_pct": "4.8%",
        "qb_knockdown": "18",
        "qb_knockdown_pct": "5.9%",
        "sacks": "12",
        "pressures": "46",
        "pressures_pct": "13.8%",
        "tackles_missed": "71"
    },
    {
        "g": "9",
        "pass_att_opp": "271",
        "pass_cmp_opp": "167",
        "pass_yds_opp": "1714",
        "pass_td_opp": "6",
        "def_tgt_yds_per_att": "8.5",
        "def_air_yds": "1017",
        "def_yac": "859",
        "blitzes": "70",
        "blitz_pct": "22.4%",
        "qb_hurry": "29",
        "qb_hurry_pct": "9.3%",
        "qb_knockdown": "33",
        "qb_knockdown_pct": "12.2%",
        "sacks": "24",
        "pressures": "86",
        "pressures_pct": "27.5%",
        "tackles_missed": "46"
    },
    {
        "g": "10",
        "pass_att_opp": "334",
        "pass_cmp_opp": "220",
        "pass_yds_opp": "2202",
        "pass_td_opp": "17",
        "def_tgt_yds_per_att": "7.7",
        "def_air_yds": "1180",
        "def_yac": "1042",
        "blitzes": "93",
        "blitz_pct": "24.6%",
        "qb_hurry": "24",
        "qb_hurry_pct": "6.3%",
        "qb_knockdown": "37",
        "qb_knockdown_pct": "11.1%",
        "sacks": "17",
        "pressures": "78",
        "pressures_pct": "20.6%",
        "tackles_missed": "65"
    },
    {
        "g": "9",
        "pass_att_opp": "264",
        "pass_cmp_opp": "158",
        "pass_yds_opp": "1851",
        "pass_td_opp": "12",
        "def_tgt_yds_per_att": "9.6",
        "def_air_yds": "1026",
        "def_yac": "962",
        "blitzes": "100",
        "blitz_pct": "32.9%",
        "qb_hurry": "29",
        "qb_hurry_pct": "9.5%",
        "qb_knockdown": "27",
        "qb_knockdown_pct": "10.2%",
        "sacks": "27",
        "pressures": "83",
        "pressures_pct": "27.3%",
        "tackles_missed": "68"
    },
    {
        "g": "10",
        "pass_att_opp": "328",
        "pass_cmp_opp": "226",
        "pass_yds_opp": "2384",
        "pass_td_opp": "14",
        "def_tgt_yds_per_att": "7.8",
        "def_air_yds": "1408",
        "def_yac": "1127",
        "blitzes": "71",
        "blitz_pct": "19.3%",
        "qb_hurry": "35",
        "qb_hurry_pct": "9.5%",
        "qb_knockdown": "29",
        "qb_knockdown_pct": "8.8%",
        "sacks": "22",
        "pressures": "86",
        "pressures_pct": "23.4%",
        "tackles_missed": "78"
    },
    {
        "g": "10",
        "pass_att_opp": "323",
        "pass_cmp_opp": "221",
        "pass_yds_opp": "2185",
        "pass_td_opp": "11",
        "def_tgt_yds_per_att": "7.2",
        "def_air_yds": "1219",
        "def_yac": "1109",
        "blitzes": "70",
        "blitz_pct": "18.9%",
        "qb_hurry": "24",
        "qb_hurry_pct": "6.5%",
        "qb_knockdown": "23",
        "qb_knockdown_pct": "7.1%",
        "sacks": "24",
        "pressures": "71",
        "pressures_pct": "19.1%",
        "tackles_missed": "53"
    },
    {
        "g": "9",
        "pass_att_opp": "243",
        "pass_cmp_opp": "163",
        "pass_yds_opp": "1897",
        "pass_td_opp": "15",
        "def_tgt_yds_per_att": "8.7",
        "def_air_yds": "914",
        "def_yac": "1134",
        "blitzes": "92",
        "blitz_pct": "32.5%",
        "qb_hurry": "31",
        "qb_hurry_pct": "11.0%",
        "qb_knockdown": "28",
        "qb_knockdown_pct": "11.5%",
        "sacks": "23",
        "pressures": "82",
        "pressures_pct": "29.0%",
        "tackles_missed": "53"
    },
    {
        "g": "10",
        "pass_att_opp": "329",
        "pass_cmp_opp": "219",
        "pass_yds_opp": "1922",
        "pass_td_opp": "12",
        "def_tgt_yds_per_att": "6.9",
        "def_air_yds": "1015",
        "def_yac": "1109",
        "blitzes": "138",
        "blitz_pct": "35.8%",
        "qb_hurry": "32",
        "qb_hurry_pct": "8.3%",
        "qb_knockdown": "38",
        "qb_knockdown_pct": "11.6%",
        "sacks": "35",
        "pressures": "105",
        "pressures_pct": "27.2%",
        "tackles_missed": "50"
    },
    {
        "g": "9",
        "pass_att_opp": "339",
        "pass_cmp_opp": "216",
        "pass_yds_opp": "2198",
        "pass_td_opp": "7",
        "def_tgt_yds_per_att": "8.1",
        "def_air_yds": "1339",
        "def_yac": "1019",
        "blitzes": "118",
        "blitz_pct": "31.1%",
        "qb_hurry": "45",
        "qb_hurry_pct": "11.8%",
        "qb_knockdown": "34",
        "qb_knockdown_pct": "10.0%",
        "sacks": "24",
        "pressures": "103",
        "pressures_pct": "27.1%",
        "tackles_missed": "53"
    },
    {
        "g": "9",
        "pass_att_opp": "282",
        "pass_cmp_opp": "183",
        "pass_yds_opp": "1863",
        "pass_td_opp": "13",
        "def_tgt_yds_per_att": "7.9",
        "def_air_yds": "1050",
        "def_yac": "949",
        "blitzes": "64",
        "blitz_pct": "19.8%",
        "qb_hurry": "34",
        "qb_hurry_pct": "10.5%",
        "qb_knockdown": "23",
        "qb_knockdown_pct": "8.2%",
        "sacks": "22",
        "pressures": "79",
        "pressures_pct": "24.5%",
        "tackles_missed": "74"
    },
    {
        "g": "10",
        "pass_att_opp": "307",
        "pass_cmp_opp": "167",
        "pass_yds_opp": "1747",
        "pass_td_opp": "21",
        "def_tgt_yds_per_att": "10.1",
        "def_air_yds": "996",
        "def_yac": "890",
        "blitzes": "100",
        "blitz_pct": "28.1%",
        "qb_hurry": "35",
        "qb_hurry_pct": "9.8%",
        "qb_knockdown": "34",
        "qb_knockdown_pct": "11.1%",
        "sacks": "29",
        "pressures": "98",
        "pressures_pct": "27.5%",
        "tackles_missed": "70"
    },
    {
        "g": "10",
        "pass_att_opp": "342",
        "pass_cmp_opp": "239",
        "pass_yds_opp": "2612",
        "pass_td_opp": "19",
        "def_tgt_yds_per_att": "7.4",
        "def_air_yds": "1356",
        "def_yac": "1382",
        "blitzes": "54",
        "blitz_pct": "13.8%",
        "qb_hurry": "25",
        "qb_hurry_pct": "6.4%",
        "qb_knockdown": "21",
        "qb_knockdown_pct": "6.1%",
        "sacks": "21",
        "pressures": "67",
        "pressures_pct": "17.2%",
        "tackles_missed": "54"
    },
    {
        "g": "9",
        "pass_att_opp": "290",
        "pass_cmp_opp": "191",
        "pass_yds_opp": "1860",
        "pass_td_opp": "13",
        "def_tgt_yds_per_att": "7.3",
        "def_air_yds": "906",
        "def_yac": "1015",
        "blitzes": "115",
        "blitz_pct": "34.5%",
        "qb_hurry": "29",
        "qb_hurry_pct": "8.7%",
        "qb_knockdown": "41",
        "qb_knockdown_pct": "14.1%",
        "sacks": "19",
        "pressures": "89",
        "pressures_pct": "26.7%",
        "tackles_missed": "49"
    },
    {
        "g": "9",
        "pass_att_opp": "274",
        "pass_cmp_opp": "174",
        "pass_yds_opp": "1722",
        "pass_td_opp": "8",
        "def_tgt_yds_per_att": "6.8",
        "def_air_yds": "963",
        "def_yac": "861",
        "blitzes": "75",
        "blitz_pct": "25.0%",
        "qb_hurry": "23",
        "qb_hurry_pct": "7.7%",
        "qb_knockdown": "21",
        "qb_knockdown_pct": "7.7%",
        "sacks": "14",
        "pressures": "58",
        "pressures_pct": "19.3%",
        "tackles_missed": "31"
    },
    {
        "g": "9",
        "pass_att_opp": "338",
        "pass_cmp_opp": "216",
        "pass_yds_opp": "2087",
        "pass_td_opp": "14",
        "def_tgt_yds_per_att": "7.6",
        "def_air_yds": "1290",
        "def_yac": "1004",
        "blitzes": "147",
        "blitz_pct": "38.9%",
        "qb_hurry": "38",
        "qb_hurry_pct": "10.1%",
        "qb_knockdown": "42",
        "qb_knockdown_pct": "12.4%",
        "sacks": "30",
        "pressures": "110",
        "pressures_pct": "29.1%",
        "tackles_missed": "42"
    },
    {
        "g": "10",
        "pass_att_opp": "343",
        "pass_cmp_opp": "218",
        "pass_yds_opp": "2446",
        "pass_td_opp": "8",
        "def_tgt_yds_per_att": "8.2",
        "def_air_yds": "1152",
        "def_yac": "1433",
        "blitzes": "84",
        "blitz_pct": "21.5%",
        "qb_hurry": "34",
        "qb_hurry_pct": "8.7%",
        "qb_knockdown": "23",
        "qb_knockdown_pct": "6.7%",
        "sacks": "22",
        "pressures": "79",
        "pressures_pct": "20.2%",
        "tackles_missed": "68"
    },
    {
        "g": "10",
        "pass_att_opp": "309",
        "pass_cmp_opp": "202",
        "pass_yds_opp": "2090",
        "pass_td_opp": "12",
        "def_tgt_yds_per_att": "8.5",
        "def_air_yds": "1330",
        "def_yac": "888",
        "blitzes": "85",
        "blitz_pct": "24.2%",
        "qb_hurry": "25",
        "qb_hurry_pct": "7.1%",
        "qb_knockdown": "21",
        "qb_knockdown_pct": "6.8%",
        "sacks": "25",
        "pressures": "71",
        "pressures_pct": "20.2%",
        "tackles_missed": "37"
    },
    {
        "g": "10",
        "pass_att_opp": "275",
        "pass_cmp_opp": "192",
        "pass_yds_opp": "1842",
        "pass_td_opp": "12",
        "def_tgt_yds_per_att": "6.5",
        "def_air_yds": "1137",
        "def_yac": "933",
        "blitzes": "94",
        "blitz_pct": "28.2%",
        "qb_hurry": "20",
        "qb_hurry_pct": "6.0%",
        "qb_knockdown": "25",
        "qb_knockdown_pct": "9.1%",
        "sacks": "36",
        "pressures": "81",
        "pressures_pct": "24.3%",
        "tackles_missed": "72"
    },
    {
        "g": "10",
        "pass_att_opp": "279",
        "pass_cmp_opp": "167",
        "pass_yds_opp": "1683",
        "pass_td_opp": "7",
        "def_tgt_yds_per_att": "9.6",
        "def_air_yds": "1076",
        "def_yac": "821",
        "blitzes": "85",
        "blitz_pct": "25.4%",
        "qb_hurry": "34",
        "qb_hurry_pct": "10.1%",
        "qb_knockdown": "24",
        "qb_knockdown_pct": "8.6%",
        "sacks": "32",
        "pressures": "90",
        "pressures_pct": "26.9%",
        "tackles_missed": "72"
    },
    {
        "g": "9",
        "pass_att_opp": "249",
        "pass_cmp_opp": "160",
        "pass_yds_opp": "1410",
        "pass_td_opp": "13",
        "def_tgt_yds_per_att": "7.0",
        "def_air_yds": "625",
        "def_yac": "912",
        "blitzes": "64",
        "blitz_pct": "22.1%",
        "qb_hurry": "18",
        "qb_hurry_pct": "6.2%",
        "qb_knockdown": "18",
        "qb_knockdown_pct": "7.2%",
        "sacks": "18",
        "pressures": "54",
        "pressures_pct": "18.7%",
        "tackles_missed": "42"
    },
    {
        "g": "9",
        "pass_att_opp": "285",
        "pass_cmp_opp": "173",
        "pass_yds_opp": "1561",
        "pass_td_opp": "8",
        "def_tgt_yds_per_att": "7.5",
        "def_air_yds": "882",
        "def_yac": "850",
        "blitzes": "67",
        "blitz_pct": "20.8%",
        "qb_hurry": "18",
        "qb_hurry_pct": "5.6%",
        "qb_knockdown": "20",
        "qb_knockdown_pct": "7.0%",
        "sacks": "25",
        "pressures": "63",
        "pressures_pct": "19.6%",
        "tackles_missed": "51"
    },
    {
        "g": "9",
        "pass_att_opp": "304",
        "pass_cmp_opp": "190",
        "pass_yds_opp": "1940",
        "pass_td_opp": "8",
        "def_tgt_yds_per_att": "7.4",
        "def_air_yds": "1055",
        "def_yac": "1055",
        "blitzes": "77",
        "blitz_pct": "23.2%",
        "qb_hurry": "15",
        "qb_hurry_pct": "4.5%",
        "qb_knockdown": "38",
        "qb_knockdown_pct": "12.5%",
        "sacks": "22",
        "pressures": "75",
        "pressures_pct": "22.6%",
        "tackles_missed": "37"
    },
    {
        "g": "9",
        "pass_att_opp": "280",
        "pass_cmp_opp": "189",
        "pass_yds_opp": "1756",
        "pass_td_opp": "15",
        "def_tgt_yds_per_att": "6.7",
        "def_air_yds": "886",
        "def_yac": "976",
        "blitzes": "92",
        "blitz_pct": "29.0%",
        "qb_hurry": "25",
        "qb_hurry_pct": "7.9%",
        "qb_knockdown": "24",
        "qb_knockdown_pct": "8.6%",
        "sacks": "17",
        "pressures": "66",
        "pressures_pct": "20.8%",
        "tackles_missed": "81"
    },
    {
        "g": "9",
        "pass_att_opp": "259",
        "pass_cmp_opp": "169",
        "pass_yds_opp": "1976",
        "pass_td_opp": "16",
        "def_tgt_yds_per_att": "8.1",
        "def_air_yds": "1159",
        "def_yac": "1013",
        "blitzes": "79",
        "blitz_pct": "26.4%",
        "qb_hurry": "37",
        "qb_hurry_pct": "12.4%",
        "qb_knockdown": "24",
        "qb_knockdown_pct": "9.3%",
        "sacks": "24",
        "pressures": "85",
        "pressures_pct": "28.4%",
        "tackles_missed": "76"
    },
    {
        "g": "10",
        "pass_att_opp": "398",
        "pass_cmp_opp": "261",
        "pass_yds_opp": "2949",
        "pass_td_opp": "22",
        "def_tgt_yds_per_att": "8.5",
        "def_air_yds": "1805",
        "def_yac": "1234",
        "blitzes": "94",
        "blitz_pct": "21.1%",
        "qb_hurry": "22",
        "qb_hurry_pct": "4.9%",
        "qb_knockdown": "43",
        "qb_knockdown_pct": "10.8%",
        "sacks": "31",
        "pressures": "96",
        "pressures_pct": "21.5%",
        "tackles_missed": "44"
    },
    {
        "g": "9",
        "pass_att_opp": "290",
        "pass_cmp_opp": "186",
        "pass_yds_opp": "1724",
        "pass_td_opp": "9",
        "def_tgt_yds_per_att": "6.8",
        "def_air_yds": "1055",
        "def_yac": "828",
        "blitzes": "76",
        "blitz_pct": "22.0%",
        "qb_hurry": "12",
        "qb_hurry_pct": "3.5%",
        "qb_knockdown": "16",
        "qb_knockdown_pct": "5.5%",
        "sacks": "31",
        "pressures": "59",
        "pressures_pct": "17.1%",
        "tackles_missed": "56"
    },
    {
        "g": "9",
        "pass_att_opp": "296",
        "pass_cmp_opp": "195",
        "pass_yds_opp": "1963",
        "pass_td_opp": "14",
        "def_tgt_yds_per_att": "6.8",
        "def_air_yds": "1019",
        "def_yac": "1092",
        "blitzes": "74",
        "blitz_pct": "22.3%",
        "qb_hurry": "27",
        "qb_hurry_pct": "8.1%",
        "qb_knockdown": "39",
        "qb_knockdown_pct": "13.2%",
        "sacks": "21",
        "pressures": "87",
        "pressures_pct": "26.2%",
        "tackles_missed": "62"
    },
    {
        "g": "9",
        "pass_att_opp": "289",
        "pass_cmp_opp": "179",
        "pass_yds_opp": "1777",
        "pass_td_opp": "11",
        "def_tgt_yds_per_att": "7.8",
        "def_air_yds": "875",
        "def_yac": "1005",
        "blitzes": "58",
        "blitz_pct": "18.1%",
        "qb_hurry": "24",
        "qb_hurry_pct": "7.5%",
    }
]
module.exports.defenseStats = defenseStats;
module.exports.advancedDefenseStats = advancedDefenseStats;
